//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public string art { get; set; }
        public string des1_art { get; set; }
        public string des2_art { get; set; }
        public string uni_art { get; set; }
        public Nullable<decimal> packsize { get; set; }
        public string cvecla { get; set; }
        public string cvescl { get; set; }
        public string linea { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public decimal NoCotiza { get; set; }
        public Nullable<decimal> Activo { get; set; }
        public Nullable<bool> Almacenable { get; set; }
    }
}
