//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_punches
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime punch_time { get; set; }
        public string workcode { get; set; }
        public string workstate { get; set; }
        public Nullable<int> terminal_id { get; set; }
        public string punch_type { get; set; }
        public string @operator { get; set; }
        public string operator_reason { get; set; }
        public Nullable<System.DateTime> operator_time { get; set; }
        public Nullable<int> iuser1 { get; set; }
        public Nullable<int> iuser2 { get; set; }
        public Nullable<int> iuser3 { get; set; }
        public string cuser1 { get; set; }
        public string cuser2 { get; set; }
        public string cuser3 { get; set; }
        public string remark { get; set; }
        public Nullable<int> IsSelect { get; set; }
    
        public virtual hr_employee hr_employee { get; set; }
    }
}
