//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_criticidad_articulos
    {
        public int id_criticidad_articulo_almacen { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> id_criticidad_tipo_operacion { get; set; }
        public Nullable<int> id_criticidad_tipo_consumo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_almacen_criticidad_tipos_consumos C_almacen_criticidad_tipos_consumos { get; set; }
        public virtual C_almacen_criticidad_tipos_operacion C_almacen_criticidad_tipos_operacion { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
    }
}
