//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_ubicaciones_articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_almacen_ubicaciones_articulos()
        {
            this.C_inventario_almacenes_articulos = new HashSet<C_inventario_almacenes_articulos>();
        }
    
        public int id_ubicacion_almacen { get; set; }
        public string nombre_ubicacion { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacenes_articulos> C_inventario_almacenes_articulos { get; set; }
    }
}
