//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_solicitudes_mercancia_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_almacen_solicitudes_mercancia_d()
        {
            this.C_almacen_solicitudes_cambios_articulos = new HashSet<C_almacen_solicitudes_cambios_articulos>();
            this.C_almacen_solicitudes_mercancia_d_logs = new HashSet<C_almacen_solicitudes_mercancia_d_logs>();
            this.C_inventario_almacen_devoluciones_d = new HashSet<C_inventario_almacen_devoluciones_d>();
        }
    
        public int id_solicitud_mercancia_d { get; set; }
        public Nullable<int> id_solicitud_mercancia_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> id_cargo_contable_g { get; set; }
        public Nullable<int> id_cuenta_contable_g { get; set; }
        public Nullable<bool> entregado { get; set; }
        public Nullable<bool> cambio_articulo { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string cargo_cuenta_contable { get; set; }
        public Nullable<decimal> cantidad_entregada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_cambios_articulos> C_almacen_solicitudes_cambios_articulos { get; set; }
        public virtual C_almacen_solicitudes_mercancia_g C_almacen_solicitudes_mercancia_g { get; set; }
        public virtual C_cargos_contables_g C_cargos_contables_g { get; set; }
        public virtual C_cuentas_contables_g C_cuentas_contables_g { get; set; }
        public virtual C_unidades_medidas C_unidades_medidas { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d_logs> C_almacen_solicitudes_mercancia_d_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_devoluciones_d> C_inventario_almacen_devoluciones_d { get; set; }
    }
}
