//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_solicitudes_mercancia_d_logs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_almacen_solicitudes_mercancia_d_logs()
        {
            this.C_inventario_almacen_devoluciones_d = new HashSet<C_inventario_almacen_devoluciones_d>();
        }
    
        public int id_solicitud_mercancia_d_log { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_solicitud_mercancia_d { get; set; }
        public Nullable<int> id_solicitud_mercancia_g { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<int> id_usuario_entrega { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_almacen_solicitudes_mercancia_d C_almacen_solicitudes_mercancia_d { get; set; }
        public virtual C_almacen_solicitudes_mercancia_g C_almacen_solicitudes_mercancia_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_devoluciones_d> C_inventario_almacen_devoluciones_d { get; set; }
    }
}
