//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_dietas_d
    {
        public int id_dieta_d { get; set; }
        public Nullable<int> id_dieta_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> porcentaje_MS { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> costo_BH { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<decimal> kilos_MS_base { get; set; }
        public Nullable<decimal> kilos_MS { get; set; }
        public Nullable<decimal> kilos_BH { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_alimentacion_dietas_g C_alimentacion_dietas_g { get; set; }
    }
}
