//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_forrajes_facturas_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_alimentacion_forrajes_facturas_g()
        {
            this.C_alimentacion_forrajes_facturas_d = new HashSet<C_alimentacion_forrajes_facturas_d>();
        }
    
        public int id_alimentacion_factura_forraje_g { get; set; }
        public string folio_factura { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<decimal> toneladas_totales { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> id_tipo_moneda { get; set; }
        public Nullable<decimal> tipo_cambio { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_forrajes_facturas_d> C_alimentacion_forrajes_facturas_d { get; set; }
        public virtual C_tipos_moneda C_tipos_moneda { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
    }
}
