//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_programa_d
    {
        public int id_alimentacion_programa_d { get; set; }
        public Nullable<int> id_alimentacion_programa_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> toneladas { get; set; }
        public Nullable<System.DateTime> fecha_programacion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_alimentacion_programa_g C_alimentacion_programa_g { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
    }
}
