//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_criticidad_tipos_consumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_almacen_criticidad_tipos_consumos()
        {
            this.C_almacen_criticidad_articulos = new HashSet<C_almacen_criticidad_articulos>();
        }
    
        public int id_criticidad_tipo_consumo { get; set; }
        public string tipo_consumo { get; set; }
        public string color { get; set; }
        public string siglas { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_criticidad_articulos> C_almacen_criticidad_articulos { get; set; }
    }
}
