//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_solicitudes_cambios_articulos
    {
        public int id_solicitud_cambio { get; set; }
        public Nullable<int> id_solicitud_d { get; set; }
        public Nullable<int> id_articulo_viejo { get; set; }
        public Nullable<int> id_articulo_nuevo { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> id_usuario_cambio { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
        public Nullable<bool> activo { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_solicitud_g { get; set; }
        public Nullable<decimal> cantidad_vieja { get; set; }
        public Nullable<decimal> cantidad_nueva { get; set; }
    
        public virtual C_almacen_solicitudes_mercancia_g C_almacen_solicitudes_mercancia_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_almacen_solicitudes_mercancia_d C_almacen_solicitudes_mercancia_d { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo1 { get; set; }
    }
}
