//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_dietas_g_valores_tipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_alimentacion_dietas_g_valores_tipos()
        {
            this.C_alimentacion_dietas_g_valores = new HashSet<C_alimentacion_dietas_g_valores>();
        }
    
        public int id_dieta_g_valor_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombre_valor_tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g_valores> C_alimentacion_dietas_g_valores { get; set; }
    }
}
