//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_envio_correos_log
    {
        public int id_trigger_correo_almacen_detalle { get; set; }
        public Nullable<int> id_trigger_correo_almacen { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_parametros_correos_almacen C_parametros_correos_almacen { get; set; }
    }
}
