//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_almacen_solicitudes_mercancia_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_almacen_solicitudes_mercancia_g()
        {
            this.C_almacen_solicitudes_cambios_articulos = new HashSet<C_almacen_solicitudes_cambios_articulos>();
            this.C_inventario_almacen_mov_g = new HashSet<C_inventario_almacen_mov_g>();
            this.C_almacen_solicitudes_mercancia_d = new HashSet<C_almacen_solicitudes_mercancia_d>();
            this.C_almacen_solicitudes_mercancia_d_logs = new HashSet<C_almacen_solicitudes_mercancia_d_logs>();
            this.C_inventario_almacen_devoluciones_g = new HashSet<C_inventario_almacen_devoluciones_g>();
        }
    
        public int id_solicitud_mercancia_g { get; set; }
        public Nullable<int> id_centro_g { get; set; }
        public Nullable<int> id_departamento_g { get; set; }
        public Nullable<int> id_almacen_g { get; set; }
        public Nullable<int> id_establo_equipo { get; set; }
        public string cargo_desc { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<decimal> total { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> autorizada { get; set; }
        public Nullable<int> id_usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_autorizacion { get; set; }
        public string justificacion { get; set; }
        public Nullable<bool> atendida { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_empleado_solicita { get; set; }
        public Nullable<int> id_status_solicitud { get; set; }
        public Nullable<int> id_usuario_entrega { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> id_alimentacion_productor { get; set; }
        public Nullable<int> id_empleado_remitente { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_almacen_solicitudes_status C_almacen_solicitudes_status { get; set; }
        public virtual C_centros_g C_centros_g { get; set; }
        public virtual C_departamentos_g C_departamentos_g { get; set; }
        public virtual C_empleados C_empleados { get; set; }
        public virtual C_establos_equipos C_establos_equipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_cambios_articulos> C_almacen_solicitudes_cambios_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_g> C_inventario_almacen_mov_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d> C_almacen_solicitudes_mercancia_d { get; set; }
        public virtual C_alimentacion_productores C_alimentacion_productores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d_logs> C_almacen_solicitudes_mercancia_d_logs { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_devoluciones_g> C_inventario_almacen_devoluciones_g { get; set; }
    }
}
