//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_forrajes_facturas_d
    {
        public int id_alimentacion_factura_forraje_d { get; set; }
        public Nullable<int> id_alimentacion_factura_forraje_g { get; set; }
        public Nullable<int> id_bascula_ficha { get; set; }
        public Nullable<decimal> toneladas_ficha { get; set; }
        public Nullable<decimal> precio_ficha { get; set; }
        public Nullable<int> id_moneda_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_alimentacion_forrajes_facturas_g C_alimentacion_forrajes_facturas_g { get; set; }
        public virtual C_tipos_moneda C_tipos_moneda { get; set; }
        public virtual C_bascula_fichas C_bascula_fichas { get; set; }
    }
}
