//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_dietas_grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_alimentacion_dietas_grupos()
        {
            this.C_alimentacion_dietas_g = new HashSet<C_alimentacion_dietas_g>();
        }
    
        public int id_dieta_grupo { get; set; }
        public string nombre_grupo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_dieta_grupo_tipo { get; set; }
    
        public virtual C_alimentacion_dietas_grupos_tipos C_alimentacion_dietas_grupos_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g { get; set; }
    }
}
