//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_alimentacion_dietas_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_alimentacion_dietas_g()
        {
            this.C_alimentacion_dietas_d = new HashSet<C_alimentacion_dietas_d>();
            this.C_alimentacion_dietas_g1 = new HashSet<C_alimentacion_dietas_g>();
            this.C_alimentacion_dietas_g_comentarios = new HashSet<C_alimentacion_dietas_g_comentarios>();
            this.C_alimentacion_dietas_g_valores = new HashSet<C_alimentacion_dietas_g_valores>();
        }
    
        public int id_dieta_g { get; set; }
        public Nullable<int> id_establo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> id_dieta_grupo { get; set; }
        public Nullable<int> id_dieta_status { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_usuario_valida { get; set; }
        public Nullable<int> id_usuario_autoriza { get; set; }
        public Nullable<int> id_dieta_g_copia { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_usuario_revisa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_d> C_alimentacion_dietas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g1 { get; set; }
        public virtual C_alimentacion_dietas_g C_alimentacion_dietas_g2 { get; set; }
        public virtual C_alimentacion_dietas_grupos C_alimentacion_dietas_grupos { get; set; }
        public virtual C_alimentacion_dietas_status C_alimentacion_dietas_status { get; set; }
        public virtual C_establos C_establos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g_comentarios> C_alimentacion_dietas_g_comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g_valores> C_alimentacion_dietas_g_valores { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo2 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo3 { get; set; }
    }
}
