//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_articulos_logs
    {
        public int id_log_articulos { get; set; }
        public Nullable<int> id_usuario_log { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public string valor_anterior { get; set; }
        public string valor_nuevo { get; set; }
        public Nullable<int> fecha_log { get; set; }
        public string descripcion_cambio { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
