//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_articulos_catalogo_bascula
    {
        public int id_articulo_bascula { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> id_ficha_tipo { get; set; }
        public Nullable<int> usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_bascula_fichas_tipos C_bascula_fichas_tipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
