//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_articulos_catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_articulos_catalogo()
        {
            this.C_almacen_solicitudes_cambios_articulos = new HashSet<C_almacen_solicitudes_cambios_articulos>();
            this.C_almacen_solicitudes_cambios_articulos1 = new HashSet<C_almacen_solicitudes_cambios_articulos>();
            this.C_almacen_solicitudes_mercancia_d = new HashSet<C_almacen_solicitudes_mercancia_d>();
            this.C_inventario_almacen_establo_maximo_minimo = new HashSet<C_inventario_almacen_establo_maximo_minimo>();
            this.C_articulos_catalogo_bascula = new HashSet<C_articulos_catalogo_bascula>();
            this.C_inventario_almacenes_articulos = new HashSet<C_inventario_almacenes_articulos>();
            this.C_articulos_precios = new HashSet<C_articulos_precios>();
            this.C_compras_requi_d = new HashSet<C_compras_requi_d>();
            this.C_inventario_almacen_captura_d = new HashSet<C_inventario_almacen_captura_d>();
            this.C_inventario_almacen_mov_d = new HashSet<C_inventario_almacen_mov_d>();
            this.C_alimentacion_articulos_precios = new HashSet<C_alimentacion_articulos_precios>();
            this.C_alimentacion_programa_d = new HashSet<C_alimentacion_programa_d>();
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
            this.C_inventario_almacen_ajustes_d = new HashSet<C_inventario_almacen_ajustes_d>();
            this.C_alimentacion_dietas_d = new HashSet<C_alimentacion_dietas_d>();
            this.C_alimentacion_tracker_articulos_ingredientes = new HashSet<C_alimentacion_tracker_articulos_ingredientes>();
            this.C_compras_cotizaciones_articulos = new HashSet<C_compras_cotizaciones_articulos>();
            this.C_compras_cotizaciones_requisiciones = new HashSet<C_compras_cotizaciones_requisiciones>();
            this.C_almacen_criticidad_articulos = new HashSet<C_almacen_criticidad_articulos>();
            this.C_inventario_almacen_mov_d_recepciones_logs = new HashSet<C_inventario_almacen_mov_d_recepciones_logs>();
        }
    
        public int id_articulo { get; set; }
        public string nombre_articulo { get; set; }
        public string descripcion_articulo { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<int> id_articulo_tipo { get; set; }
        public Nullable<int> id_articulo_clasificacion { get; set; }
        public Nullable<int> id_articulo_linea { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> almacenable { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_articulo_tipo_requisicion { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_marca { get; set; }
        public Nullable<bool> disponible_bascula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_cambios_articulos> C_almacen_solicitudes_cambios_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_cambios_articulos> C_almacen_solicitudes_cambios_articulos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d> C_almacen_solicitudes_mercancia_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_establo_maximo_minimo> C_inventario_almacen_establo_maximo_minimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_articulos_catalogo_bascula> C_articulos_catalogo_bascula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacenes_articulos> C_inventario_almacenes_articulos { get; set; }
        public virtual C_articulos_clasificaciones C_articulos_clasificaciones { get; set; }
        public virtual C_articulos_lineas C_articulos_lineas { get; set; }
        public virtual C_articulos_tipos C_articulos_tipos { get; set; }
        public virtual C_articulos_tipos_requisicion C_articulos_tipos_requisicion { get; set; }
        public virtual C_unidades_medidas C_unidades_medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_articulos_precios> C_articulos_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_d> C_compras_requi_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_captura_d> C_inventario_almacen_captura_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d> C_inventario_almacen_mov_d { get; set; }
        public virtual C_articulos_marcas C_articulos_marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_articulos_precios> C_alimentacion_articulos_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_programa_d> C_alimentacion_programa_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_ajustes_d> C_inventario_almacen_ajustes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_d> C_alimentacion_dietas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_tracker_articulos_ingredientes> C_alimentacion_tracker_articulos_ingredientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_articulos> C_compras_cotizaciones_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_requisiciones> C_compras_cotizaciones_requisiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_criticidad_articulos> C_almacen_criticidad_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d_recepciones_logs> C_inventario_almacen_mov_d_recepciones_logs { get; set; }
    }
}
