//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_establos_fichas_tipos
    {
        public int id_bascula_establo_tipo_ficha { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<int> id_ficha_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_bascula_fichas_tipos C_bascula_fichas_tipos { get; set; }
        public virtual C_establos C_establos { get; set; }
    }
}
