//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_lineas_transportistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bascula_lineas_transportistas()
        {
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
            this.C_envios_leche_programacion_semanal_cliente_d_dias_horas = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias_horas>();
        }
    
        public int id_bascula_linea_transp { get; set; }
        public string nombre_linea { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias_horas> C_envios_leche_programacion_semanal_cliente_d_dias_horas { get; set; }
    }
}
