//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_codigos_movimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bascula_codigos_movimientos()
        {
            this.C_bascula_establos_codigos_movimientos = new HashSet<C_bascula_establos_codigos_movimientos>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
        }
    
        public int id_bascula_codigo_movimiento { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public string codigo_mov { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_bascula_tipos_movimientos C_bascula_tipos_movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_establos_codigos_movimientos> C_bascula_establos_codigos_movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
    }
}
