//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_fichas_tipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bascula_fichas_tipos()
        {
            this.C_articulos_catalogo_bascula = new HashSet<C_articulos_catalogo_bascula>();
            this.C_bascula_establos_fichas_tipos = new HashSet<C_bascula_establos_fichas_tipos>();
            this.C_bascula_establos_codigos_movimientos = new HashSet<C_bascula_establos_codigos_movimientos>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
        }
    
        public int id_ficha_tipo { get; set; }
        public string tipo_ficha { get; set; }
        public Nullable<int> tipo_catalogo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_articulos_catalogo_bascula> C_articulos_catalogo_bascula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_establos_fichas_tipos> C_bascula_establos_fichas_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_establos_codigos_movimientos> C_bascula_establos_codigos_movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
    }
}
