//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_no_pozos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bascula_no_pozos()
        {
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
        }
    
        public int id_no_pozo { get; set; }
        public string no_pozo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_establo { get; set; }
    
        public virtual C_establos C_establos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
    }
}
