//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bascula_fichas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_bascula_fichas()
        {
            this.C_alimentacion_forrajes_facturas_d = new HashSet<C_alimentacion_forrajes_facturas_d>();
            this.C_envios_leche_d_fichas = new HashSet<C_envios_leche_d_fichas>();
        }
    
        public int id_bascula_ficha { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<int> id_ficha_tipo { get; set; }
        public Nullable<int> id_articulo_bascula { get; set; }
        public Nullable<int> id_envio_leche_cliente_ms { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_registo { get; set; }
        public string folio { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_codigo_movimiento { get; set; }
        public Nullable<decimal> peso_1 { get; set; }
        public Nullable<decimal> peso_2 { get; set; }
        public Nullable<decimal> peso_t { get; set; }
        public string observaciones { get; set; }
        public Nullable<decimal> peso_origen { get; set; }
        public Nullable<decimal> peso_materia_seca { get; set; }
        public string chofer { get; set; }
        public Nullable<int> id_linea_transportista { get; set; }
        public string placas { get; set; }
        public string placas_pipa { get; set; }
        public string maquilador { get; set; }
        public string predio_cliente { get; set; }
        public Nullable<int> id_no_pozo { get; set; }
        public Nullable<System.DateTime> fecha_segunda_pesada { get; set; }
        public Nullable<int> id_tipo_movimiento { get; set; }
        public Nullable<bool> agrupada { get; set; }
        public Nullable<bool> termina { get; set; }
        public string sucursal { get; set; }
        public string destino { get; set; }
        public string tabla { get; set; }
        public string variedad { get; set; }
        public string ensilador { get; set; }
        public string corte { get; set; }
        public string pacas { get; set; }
        public Nullable<bool> recibido { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_forrajes_facturas_d> C_alimentacion_forrajes_facturas_d { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_bascula_codigos_movimientos C_bascula_codigos_movimientos { get; set; }
        public virtual C_bascula_fichas_tipos C_bascula_fichas_tipos { get; set; }
        public virtual C_envios_leche_clientes C_envios_leche_clientes { get; set; }
        public virtual C_establos C_establos { get; set; }
        public virtual C_bascula_lineas_transportistas C_bascula_lineas_transportistas { get; set; }
        public virtual C_bascula_no_pozos C_bascula_no_pozos { get; set; }
        public virtual C_bascula_tipos_movimientos C_bascula_tipos_movimientos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_d_fichas> C_envios_leche_d_fichas { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
    }
}
