//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cargos_contables_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_cargos_contables_g()
        {
            this.C_cuentas_contables_g = new HashSet<C_cuentas_contables_g>();
            this.C_firmas_usuarios = new HashSet<C_firmas_usuarios>();
            this.C_usuarios_cargos_contables = new HashSet<C_usuarios_cargos_contables>();
            this.C_almacen_solicitudes_mercancia_d = new HashSet<C_almacen_solicitudes_mercancia_d>();
            this.C_compras_requi_d = new HashSet<C_compras_requi_d>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
        }
    
        public int id_cargo_contable_g { get; set; }
        public string nombre_cargo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_cuentas_contables_g> C_cuentas_contables_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_firmas_usuarios> C_firmas_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_cargos_contables> C_usuarios_cargos_contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d> C_almacen_solicitudes_mercancia_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_d> C_compras_requi_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
    }
}
