//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_centros_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_centros_g()
        {
            this.C_almacen_solicitudes_mercancia_g = new HashSet<C_almacen_solicitudes_mercancia_g>();
            this.C_usuarios_centros = new HashSet<C_usuarios_centros>();
            this.C_compras_requi_g = new HashSet<C_compras_requi_g>();
            this.C_almacen_almacenes_centros = new HashSet<C_almacen_almacenes_centros>();
            this.C_compras_requi_d = new HashSet<C_compras_requi_d>();
            this.C_compras_ordenes_g = new HashSet<C_compras_ordenes_g>();
        }
    
        public int id_centro_g { get; set; }
        public string nombre_centro { get; set; }
        public string siglas { get; set; }
        public Nullable<int> id_empleado_encargado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_empleados C_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_centros> C_usuarios_centros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_almacenes_centros> C_almacen_almacenes_centros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_d> C_compras_requi_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_g> C_compras_ordenes_g { get; set; }
    }
}
