//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_recepciones_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_recepciones_g()
        {
            this.C_compras_ordenes_precarga_g = new HashSet<C_compras_ordenes_precarga_g>();
            this.C_compras_ordenes_recepciones_d = new HashSet<C_compras_ordenes_recepciones_d>();
        }
    
        public int id_compras_orden_recepcion_g { get; set; }
        public Nullable<int> id_compras_orden_g { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> factura_remision { get; set; }
        public string factura_remision_folio { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_compras_ordenes_g C_compras_ordenes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_g> C_compras_ordenes_precarga_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_recepciones_d> C_compras_ordenes_recepciones_d { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
