//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_requi_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_requi_d()
        {
            this.C_compras_cotizaciones_requisiciones = new HashSet<C_compras_cotizaciones_requisiciones>();
        }
    
        public int id_requisicion_articulo_d { get; set; }
        public Nullable<int> id_requisicion_articulo_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public string nombre_art { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public string observacion { get; set; }
        public Nullable<int> id_centro_g { get; set; }
        public Nullable<int> id_cargo_contable { get; set; }
        public Nullable<int> id_cuenta_contable_g { get; set; }
        public Nullable<bool> cotizado { get; set; }
        public Nullable<decimal> cantidad_cotizada { get; set; }
        public Nullable<bool> recotizado { get; set; }
    
        public virtual C_cargos_contables_g C_cargos_contables_g { get; set; }
        public virtual C_centros_g C_centros_g { get; set; }
        public virtual C_compras_requi_g C_compras_requi_g { get; set; }
        public virtual C_cuentas_contables_g C_cuentas_contables_g { get; set; }
        public virtual C_unidades_medidas C_unidades_medidas { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_requisiciones> C_compras_cotizaciones_requisiciones { get; set; }
    }
}
