//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_facturas_proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_facturas_proveedores()
        {
            this.C_contabilidad_importacion_facturas_d = new HashSet<C_contabilidad_importacion_facturas_d>();
        }
    
        public int id_factura_orden { get; set; }
        public Nullable<int> id_compras_orden_g { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<int> id_proveedor_microsip { get; set; }
        public string folio_factura { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> iva_monto { get; set; }
        public Nullable<decimal> iva_retenido_monto { get; set; }
        public Nullable<decimal> iva_retenido_porcentaje { get; set; }
        public Nullable<decimal> iva_retenido_base { get; set; }
        public Nullable<decimal> isr_monto { get; set; }
        public Nullable<decimal> isr_retenido_porcentaje { get; set; }
        public Nullable<decimal> isr_retenido_base { get; set; }
        public Nullable<decimal> total { get; set; }
        public string moneda { get; set; }
        public Nullable<bool> aplicado { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<decimal> ieps_monto { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> total_calculado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_importacion_facturas_d> C_contabilidad_importacion_facturas_d { get; set; }
        public virtual C_compras_ordenes_g C_compras_ordenes_g { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
    }
}
