//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_proveedores_portal_tokens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_proveedores_portal_tokens()
        {
            this.C_compras_proveedores_portal_solicitudes = new HashSet<C_compras_proveedores_portal_solicitudes>();
        }
    
        public int id_codigo_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public Nullable<int> id_usuario_registro { get; set; }
        public string codigo_token { get; set; }
        public Nullable<bool> ejercido { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_ejercido { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores_portal_solicitudes> C_compras_proveedores_portal_solicitudes { get; set; }
    }
}
