//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_contabilidad_solicitudes_pago_d
    {
        public int id_solicitud_pago_d { get; set; }
        public Nullable<int> id_solicitud_pago_g { get; set; }
        public Nullable<int> id_docto_ba { get; set; }
        public Nullable<int> id_docto_cp { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_concepto { get; set; }
        public string concepto_nombre { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> importe_detalle { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public string moneda_nombre { get; set; }
        public string moneda_clave_fiscal { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_beneficiario { get; set; }
        public string beneficiario_nombre { get; set; }
        public string cuenta_bancaria { get; set; }
        public string nombre_pf { get; set; }
        public string tipo_persona { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_contabilidad_solicitudes_pago_g C_contabilidad_solicitudes_pago_g { get; set; }
    }
}
