//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_contabilidad_solicitudes_pago_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_contabilidad_solicitudes_pago_g()
        {
            this.C_contabilidad_solicitudes_pago_d = new HashSet<C_contabilidad_solicitudes_pago_d>();
        }
    
        public int id_solicitud_pago_g { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string numero_cuenta { get; set; }
        public string moneda_clave_fiscal { get; set; }
        public string referencia { get; set; }
        public Nullable<int> id_usuario_aut1 { get; set; }
        public Nullable<int> id_usuario_aut2 { get; set; }
        public Nullable<int> id_solicitudes_pago_status { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> generacion_txt_interbancario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_solicitudes_pago_d> C_contabilidad_solicitudes_pago_d { get; set; }
        public virtual C_contabilidad_solicitudes_pago_status C_contabilidad_solicitudes_pago_status { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo2 { get; set; }
    }
}
