//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_proveedores_portal_solicitudes
    {
        public int id_proveedor_solicitud { get; set; }
        public string nombre_proveedor { get; set; }
        public string razon_social { get; set; }
        public string RFC { get; set; }
        public string correo { get; set; }
        public string nombre_contacto { get; set; }
        public string telefono { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> id_tipo_proveedor_giro { get; set; }
        public string calle { get; set; }
        public string no_exterior { get; set; }
        public string colonia { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_pais { get; set; }
        public string codigo_postal { get; set; }
        public Nullable<int> id_banco { get; set; }
        public string banco { get; set; }
        public string clave_interbancaria { get; set; }
        public Nullable<int> id_tipo_persona { get; set; }
        public string nombre_persona_fisica { get; set; }
        public Nullable<int> id_codigo_proveedor { get; set; }
        public string path_rfc { get; set; }
        public string path_estado_cuenta { get; set; }
        public string path_cuenta_clave { get; set; }
        public string path_positivo_32D { get; set; }
        public Nullable<int> id_proveedor_solicitud_status { get; set; }
        public Nullable<bool> importada_MS { get; set; }
        public Nullable<int> id_proveedor_ms { get; set; }
        public string path_acta_cons { get; set; }
        public string path_acta_poder { get; set; }
        public string path_idnt_apoderado { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_compras_proveedores_portal_solicitudes_status C_compras_proveedores_portal_solicitudes_status { get; set; }
        public virtual C_compras_proveedores_portal_tokens C_compras_proveedores_portal_tokens { get; set; }
        public virtual C_direcciones_ciudades C_direcciones_ciudades { get; set; }
        public virtual C_direcciones_estados C_direcciones_estados { get; set; }
        public virtual C_direcciones_paises C_direcciones_paises { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
    }
}
