//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_cotizaciones_articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_cotizaciones_articulos()
        {
            this.C_compras_cotizaciones_requisiciones = new HashSet<C_compras_cotizaciones_requisiciones>();
        }
    
        public int id_compra_articulo_cotizacion { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> porcentaje_descuento { get; set; }
        public Nullable<decimal> precio_final { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public Nullable<System.DateTime> fecha_cotizacion { get; set; }
        public Nullable<System.DateTime> fecha_vigencia { get; set; }
        public Nullable<int> id_usuario_cotiza { get; set; }
        public Nullable<int> id_tipo_moneda { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> dias_entrega { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
        public virtual C_tipos_moneda C_tipos_moneda { get; set; }
        public virtual C_unidades_medidas C_unidades_medidas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_requisiciones> C_compras_cotizaciones_requisiciones { get; set; }
    }
}
