//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_cotizaciones_requisiciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_cotizaciones_requisiciones()
        {
            this.C_compras_cotizaciones_confirmadas_d = new HashSet<C_compras_cotizaciones_confirmadas_d>();
        }
    
        public int id_cotizacion_requisicion { get; set; }
        public Nullable<int> id_requisicion_articulo_g { get; set; }
        public Nullable<int> id_compra_articulo_cotizacion { get; set; }
        public Nullable<int> dias_entrega { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_confirmacion { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> confirmada { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_requisicion_articulo_d { get; set; }
        public Nullable<int> id_usuario_actualizo { get; set; }
        public Nullable<bool> agrupada { get; set; }
        public Nullable<decimal> cantidad_surtir { get; set; }
        public Nullable<bool> orden_generada { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_compras_cotizaciones_articulos C_compras_cotizaciones_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_confirmadas_d> C_compras_cotizaciones_confirmadas_d { get; set; }
        public virtual C_compras_cotizaciones_requisiciones C_compras_cotizaciones_requisiciones1 { get; set; }
        public virtual C_compras_cotizaciones_requisiciones C_compras_cotizaciones_requisiciones2 { get; set; }
        public virtual C_compras_requi_d C_compras_requi_d { get; set; }
        public virtual C_compras_requi_g C_compras_requi_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
    }
}
