//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_inversiones_programadas
    {
        public int id_compra_inversion_programada { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> presupuesto { get; set; }
        public Nullable<System.DateTime> fecha_aplicacion { get; set; }
        public Nullable<bool> aplicado { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_requisicion_articulo_g { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_aplica { get; set; }
        public Nullable<System.DateTime> fecha_aplica { get; set; }
        public string folio_inversion_requi { get; set; }
    
        public virtual C_compras_requi_g C_compras_requi_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
    }
}
