//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_d()
        {
            this.C_compras_ordenes_recepciones_d = new HashSet<C_compras_ordenes_recepciones_d>();
            this.C_compras_ordenes_precarga_d = new HashSet<C_compras_ordenes_precarga_d>();
        }
    
        public int id_compras_orden_d { get; set; }
        public Nullable<int> id_compras_orden_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> cantidad_compra { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<int> id_tipo_moneda { get; set; }
        public Nullable<int> id_cargo_contable { get; set; }
        public Nullable<int> id_cuenta_contable { get; set; }
        public string nombre_articulo { get; set; }
        public Nullable<int> id_unidad_medida { get; set; }
        public Nullable<decimal> cantidad_entregada { get; set; }
        public Nullable<bool> entregado { get; set; }
        public Nullable<decimal> cantidad_precarga { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_cargos_contables_g C_cargos_contables_g { get; set; }
        public virtual C_compras_ordenes_g C_compras_ordenes_g { get; set; }
        public virtual C_cuentas_contables_g C_cuentas_contables_g { get; set; }
        public virtual C_tipos_moneda C_tipos_moneda { get; set; }
        public virtual C_unidades_medidas C_unidades_medidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_recepciones_d> C_compras_ordenes_recepciones_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_d> C_compras_ordenes_precarga_d { get; set; }
    }
}
