//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_precarga_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_precarga_g()
        {
            this.C_compras_ordenes_precarga_d = new HashSet<C_compras_ordenes_precarga_d>();
        }
    
        public int id_precarga_g { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_usuario_edita { get; set; }
        public Nullable<int> id_compras_orden_g { get; set; }
        public Nullable<bool> recibido { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_compras_orden_recepcion_g { get; set; }
        public Nullable<int> id_empleado_repartidor { get; set; }
        public string comentario { get; set; }
    
        public virtual C_compras_ordenes_g C_compras_ordenes_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_d> C_compras_ordenes_precarga_d { get; set; }
        public virtual C_compras_ordenes_recepciones_g C_compras_ordenes_recepciones_g { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
    }
}
