//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_cotizaciones_confirmadas_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_cotizaciones_confirmadas_g()
        {
            this.C_compras_cotizaciones_confirmadas_d = new HashSet<C_compras_cotizaciones_confirmadas_d>();
            this.C_compras_ordenes_g = new HashSet<C_compras_ordenes_g>();
        }
    
        public int id_cotizacion_confirmada_g { get; set; }
        public Nullable<int> id_requisicion_articulo_g { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> confirmada { get; set; }
        public string nombre_suborden { get; set; }
        public Nullable<int> id_status_cotizacion_confirmada { get; set; }
        public Nullable<bool> solicita_autorizacion { get; set; }
        public Nullable<int> id_compras_ubicacion_entrega { get; set; }
        public string correo_proveedor_suborden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_confirmadas_d> C_compras_cotizaciones_confirmadas_d { get; set; }
        public virtual C_compras_cotizaciones_confirmadas_status C_compras_cotizaciones_confirmadas_status { get; set; }
        public virtual C_compras_ordenes_ubicaciones_entrega C_compras_ordenes_ubicaciones_entrega { get; set; }
        public virtual C_compras_requi_g C_compras_requi_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_g> C_compras_ordenes_g { get; set; }
    }
}
