//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_g()
        {
            this.C_compras_facturas_proveedores = new HashSet<C_compras_facturas_proveedores>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
            this.C_inventario_almacen_mov_g = new HashSet<C_inventario_almacen_mov_g>();
            this.C_compras_ordenes_precarga_g = new HashSet<C_compras_ordenes_precarga_g>();
            this.C_compras_ordenes_recepciones_g = new HashSet<C_compras_ordenes_recepciones_g>();
        }
    
        public int id_compras_orden_g { get; set; }
        public Nullable<int> id_requisicion_articulo_g { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_cotizacion_confirmada_g { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_genera { get; set; }
        public Nullable<int> id_centro { get; set; }
        public Nullable<int> id_tipo_orden { get; set; }
        public Nullable<int> id_status_orden { get; set; }
        public Nullable<bool> entregado { get; set; }
        public Nullable<bool> activo { get; set; }
        public string token_orden { get; set; }
        public Nullable<int> id_compras_ubicacion_entrega { get; set; }
        public Nullable<bool> alta_proveedor { get; set; }
        public Nullable<int> id_usuario_recepciona { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
    
        public virtual C_centros_g C_centros_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_facturas_proveedores> C_compras_facturas_proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
        public virtual C_compras_ordenes_status C_compras_ordenes_status { get; set; }
        public virtual C_compras_ordenes_ubicaciones_entrega C_compras_ordenes_ubicaciones_entrega { get; set; }
        public virtual C_compras_requi_g C_compras_requi_g { get; set; }
        public virtual C_compras_requisiciones_tipos C_compras_requisiciones_tipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_g> C_inventario_almacen_mov_g { get; set; }
        public virtual C_compras_cotizaciones_confirmadas_g C_compras_cotizaciones_confirmadas_g { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_g> C_compras_ordenes_precarga_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_recepciones_g> C_compras_ordenes_recepciones_g { get; set; }
    }
}
