//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_cotizaciones_confirmadas_d
    {
        public int id_cotizacion_confirmada_d { get; set; }
        public Nullable<int> id_cotizacion_confirmada_g { get; set; }
        public Nullable<int> id_cotizacion_requisicion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_compras_cotizaciones_confirmadas_g C_compras_cotizaciones_confirmadas_g { get; set; }
        public virtual C_compras_cotizaciones_requisiciones C_compras_cotizaciones_requisiciones { get; set; }
    }
}
