//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_precarga_d
    {
        public int id_precarga_d { get; set; }
        public Nullable<int> id_precarga_g { get; set; }
        public Nullable<decimal> cantidad_compra { get; set; }
        public Nullable<decimal> cantidad_entrega { get; set; }
        public Nullable<decimal> cantidad_precarga { get; set; }
        public Nullable<int> id_compras_orden_d { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_compras_orden_recepcion_d { get; set; }
    
        public virtual C_compras_ordenes_d C_compras_ordenes_d { get; set; }
        public virtual C_compras_ordenes_precarga_g C_compras_ordenes_precarga_g { get; set; }
        public virtual C_compras_ordenes_recepciones_d C_compras_ordenes_recepciones_d { get; set; }
    }
}
