//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_ubicaciones_entrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_ubicaciones_entrega()
        {
            this.C_almacen_almacenes_ubicaciones_entrega = new HashSet<C_almacen_almacenes_ubicaciones_entrega>();
            this.C_compras_ordenes_g = new HashSet<C_compras_ordenes_g>();
            this.C_compras_cotizaciones_confirmadas_g = new HashSet<C_compras_cotizaciones_confirmadas_g>();
        }
    
        public int id_compras_ubicacion_entrega { get; set; }
        public string nombre_ubicacion { get; set; }
        public string color { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_almacenes_ubicaciones_entrega> C_almacen_almacenes_ubicaciones_entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_g> C_compras_ordenes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_confirmadas_g> C_compras_cotizaciones_confirmadas_g { get; set; }
    }
}
