//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_contabilidad_importacion_facturas_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_contabilidad_importacion_facturas_g()
        {
            this.C_contabilidad_importacion_facturas_d = new HashSet<C_contabilidad_importacion_facturas_d>();
        }
    
        public int id_contabilidad_importacion_g { get; set; }
        public string nombre_importacion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registro { get; set; }
        public Nullable<int> facturas_aceptadas { get; set; }
        public Nullable<int> facturas_rechazadas { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> facturas_importadas { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_importacion_facturas_d> C_contabilidad_importacion_facturas_d { get; set; }
    }
}
