//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_compras_ordenes_recepciones_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_compras_ordenes_recepciones_d()
        {
            this.C_compras_ordenes_precarga_d = new HashSet<C_compras_ordenes_precarga_d>();
        }
    
        public int id_compras_orden_recepcion_d { get; set; }
        public Nullable<int> id_compras_orden_recepcion_g { get; set; }
        public Nullable<int> id_compras_orden_d { get; set; }
        public Nullable<decimal> cantidad_recepcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_compras_ordenes_d C_compras_ordenes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_d> C_compras_ordenes_precarga_d { get; set; }
        public virtual C_compras_ordenes_recepciones_g C_compras_ordenes_recepciones_g { get; set; }
    }
}
