//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cuentas_contables_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_cuentas_contables_g()
        {
            this.C_presupuestos_cuentas_meses_anios = new HashSet<C_presupuestos_cuentas_meses_anios>();
            this.C_presupuestos_almacenes_cuentas_meses_anios = new HashSet<C_presupuestos_almacenes_cuentas_meses_anios>();
            this.C_almacen_solicitudes_mercancia_d = new HashSet<C_almacen_solicitudes_mercancia_d>();
            this.C_compras_requi_d = new HashSet<C_compras_requi_d>();
            this.C_contabilidad_importacion_facturas_d = new HashSet<C_contabilidad_importacion_facturas_d>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
            this.C_usuarios_cuentas_contables = new HashSet<C_usuarios_cuentas_contables>();
        }
    
        public int id_cuenta_contable { get; set; }
        public string nombre_cuenta { get; set; }
        public Nullable<bool> activo { get; set; }
        public string cuenta { get; set; }
        public Nullable<int> id_cargo_contable { get; set; }
        public Nullable<int> id_almacen_g { get; set; }
    
        public virtual C_cargos_contables_g C_cargos_contables_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_cuentas_meses_anios> C_presupuestos_cuentas_meses_anios { get; set; }
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_cuentas_contables_g C_cuentas_contables_g1 { get; set; }
        public virtual C_cuentas_contables_g C_cuentas_contables_g2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_almacenes_cuentas_meses_anios> C_presupuestos_almacenes_cuentas_meses_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d> C_almacen_solicitudes_mercancia_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_d> C_compras_requi_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_importacion_facturas_d> C_contabilidad_importacion_facturas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_cuentas_contables> C_usuarios_cuentas_contables { get; set; }
    }
}
