//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_direcciones_estados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_direcciones_estados()
        {
            this.C_direcciones_ciudades = new HashSet<C_direcciones_ciudades>();
            this.C_compras_proveedores_portal_solicitudes = new HashSet<C_compras_proveedores_portal_solicitudes>();
        }
    
        public int id_estado { get; set; }
        public string nombre_estado { get; set; }
        public string abreviacion { get; set; }
        public Nullable<int> id_pais { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_direcciones_ciudades> C_direcciones_ciudades { get; set; }
        public virtual C_direcciones_paises C_direcciones_paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores_portal_solicitudes> C_compras_proveedores_portal_solicitudes { get; set; }
    }
}
