//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dispositivos_comandos_globales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_dispositivos_comandos_globales()
        {
            this.C_dispositivos_comandos_ejecutados = new HashSet<C_dispositivos_comandos_ejecutados>();
        }
    
        public int id_comando_global { get; set; }
        public Nullable<int> id_comando { get; set; }
        public string parametro { get; set; }
        public Nullable<bool> para_todos { get; set; }
        public string para_mac { get; set; }
        public Nullable<int> para_tipo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<bool> es_perpetuo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_dispositivos_comandos_catalogo C_dispositivos_comandos_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_dispositivos_comandos_ejecutados> C_dispositivos_comandos_ejecutados { get; set; }
        public virtual C_dispositivos_tipos C_dispositivos_tipos { get; set; }
    }
}
