//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dispositivos_modulos_items
    {
        public int id_modulo_item { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public string descripcion { get; set; }
        public string id_android_menu_item { get; set; }
        public string funcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_dispositivos_modulos C_dispositivos_modulos { get; set; }
    }
}
