//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dispositivos_latidos
    {
        public int id { get; set; }
        public string mac_address { get; set; }
        public string version_app { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
