//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dispositivos_tipos_modulo
    {
        public int id_tipo_modulo { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public Nullable<int> id_dispositivo_tipo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_dispositivos_modulos C_dispositivos_modulos { get; set; }
        public virtual C_dispositivos_tipos C_dispositivos_tipos { get; set; }
    }
}
