//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_direcciones_ciudades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_direcciones_ciudades()
        {
            this.C_nomina_empleados_solicitudes = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_empleados_solicitudes1 = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_empleados = new HashSet<C_nomina_empleados>();
            this.C_nomina_empleados1 = new HashSet<C_nomina_empleados>();
            this.C_compras_proveedores_portal_solicitudes = new HashSet<C_compras_proveedores_portal_solicitudes>();
        }
    
        public int id_ciudad { get; set; }
        public string nombre_ciudad { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_direcciones_estados C_direcciones_estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados> C_nomina_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados> C_nomina_empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores_portal_solicitudes> C_compras_proveedores_portal_solicitudes { get; set; }
    }
}
