//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dispositivos_comandos_ejecutados
    {
        public int id_ejecucion { get; set; }
        public Nullable<int> id_comando_global { get; set; }
        public string mac_address { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
    
        public virtual C_dispositivos_comandos_globales C_dispositivos_comandos_globales { get; set; }
    }
}
