//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_empresas_patrones
    {
        public int id_patron_empresa { get; set; }
        public string nombre_patron { get; set; }
        public string registro_patronal { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_empresas C_empresas { get; set; }
    }
}
