//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_silos_establo
    {
        public int id_envio_leche_silo_establo { get; set; }
        public Nullable<int> id_envio_leche_silo { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_silos C_envios_leche_silos { get; set; }
        public virtual C_establos C_establos { get; set; }
    }
}
