//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_tipos_tanques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_tipos_tanques()
        {
            this.C_establos_caseta_logs_d_visita_bascula = new HashSet<C_establos_caseta_logs_d_visita_bascula>();
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
            this.C_envios_leche_programacion_semanal_cliente_d_dias_horas = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias_horas>();
        }
    
        public int id_tipo_tanque_pipa { get; set; }
        public string tipo_tanque { get; set; }
        public string color { get; set; }
        public Nullable<short> numero_pipas { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_d_visita_bascula> C_establos_caseta_logs_d_visita_bascula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias_horas> C_envios_leche_programacion_semanal_cliente_d_dias_horas { get; set; }
    }
}
