//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_destinos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_destinos()
        {
            this.C_envios_leche_cliente_destinos = new HashSet<C_envios_leche_cliente_destinos>();
            this.C_envios_leche_programacion_semanal_cliente_d = new HashSet<C_envios_leche_programacion_semanal_cliente_d>();
            this.C_envios_leche_precios = new HashSet<C_envios_leche_precios>();
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
        }
    
        public int id_destino_envio_leche { get; set; }
        public string nombre_destino { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cliente_destinos> C_envios_leche_cliente_destinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d> C_envios_leche_programacion_semanal_cliente_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_precios> C_envios_leche_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
    }
}
