//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_cumplimiento_semanal_comentario
    {
        public int id_cumplimiento_semanal_comentario { get; set; }
        public Nullable<int> id_cumplimiento_semanal { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_cumplimiento_semanal C_envios_leche_cumplimiento_semanal { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
