//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_programacion_semanal_cliente_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_programacion_semanal_cliente_d()
        {
            this.C_envios_leche_programacion_semanal_cliente_d_dias = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias>();
        }
    
        public int id_programacion_semanal_cliente_d { get; set; }
        public Nullable<int> id_programacion_semanal_cliente_g { get; set; }
        public Nullable<int> id_cliente_envio_leche { get; set; }
        public Nullable<int> id_destino_envio_leche { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_clientes C_envios_leche_clientes { get; set; }
        public virtual C_envios_leche_destinos C_envios_leche_destinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias> C_envios_leche_programacion_semanal_cliente_d_dias { get; set; }
        public virtual C_establos C_establos { get; set; }
        public virtual C_envios_leche_programacion_semanal_g C_envios_leche_programacion_semanal_g { get; set; }
    }
}
