//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_d_fichas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_d_fichas()
        {
            this.C_envios_leche_d_calidad = new HashSet<C_envios_leche_d_calidad>();
        }
    
        public int id_envio_leche_d { get; set; }
        public Nullable<int> id_envio_leche_g { get; set; }
        public Nullable<int> id_ficha_bascula { get; set; }
        public string folio_ficha { get; set; }
        public string tanque { get; set; }
        public Nullable<decimal> kilos_ficha { get; set; }
        public Nullable<decimal> litros_ficha { get; set; }
        public string sello { get; set; }
        public Nullable<decimal> litros_confirmacion { get; set; }
        public string folio_confirmacion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_bascula_fichas C_bascula_fichas { get; set; }
        public virtual C_envios_leche_g C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_d_calidad> C_envios_leche_d_calidad { get; set; }
    }
}
