//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_confirmacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_confirmacion()
        {
            this.C_envios_leche_lote_d = new HashSet<C_envios_leche_lote_d>();
        }
    
        public int id_envio_leche_confirmacion { get; set; }
        public Nullable<int> id_envio_leche_g { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<int> id_envio_leche_confirmacion_status { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_g C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_lote_d> C_envios_leche_lote_d { get; set; }
        public virtual C_envios_leche_status C_envios_leche_status { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
