//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_cliente_destinos
    {
        public int id_cliente_destino { get; set; }
        public Nullable<int> id_envio_leche_cliente_ms { get; set; }
        public Nullable<int> id_destino_envio_leche { get; set; }
        public Nullable<int> usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_destinos C_envios_leche_destinos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_envios_leche_clientes C_envios_leche_clientes { get; set; }
    }
}
