//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_cumplimiento_semanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_cumplimiento_semanal()
        {
            this.C_envios_leche_cumplimiento_semanal_comentario = new HashSet<C_envios_leche_cumplimiento_semanal_comentario>();
        }
    
        public int id_cumplimiento_semanal { get; set; }
        public Nullable<int> id_cumplimiento_mensual { get; set; }
        public Nullable<int> no_semana { get; set; }
        public string comentario { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_cumplimiento_mensual C_envios_leche_cumplimiento_mensual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_semanal_comentario> C_envios_leche_cumplimiento_semanal_comentario { get; set; }
    }
}
