//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_d_calidad
    {
        public int id_envio_leche_d_calidad { get; set; }
        public Nullable<int> id_envio_leche_d_ficha { get; set; }
        public string muestra_calidad { get; set; }
        public Nullable<decimal> temperatura { get; set; }
        public string sala { get; set; }
        public Nullable<decimal> proteina { get; set; }
        public Nullable<decimal> lactosa { get; set; }
        public Nullable<decimal> crioscopia { get; set; }
        public Nullable<decimal> solidos_no_grasos { get; set; }
        public Nullable<decimal> caseina { get; set; }
        public Nullable<decimal> urea { get; set; }
        public Nullable<decimal> grasa { get; set; }
        public Nullable<decimal> solidos_totales { get; set; }
        public Nullable<decimal> acidez { get; set; }
        public Nullable<decimal> ccs { get; set; }
        public Nullable<int> antibiotico { get; set; }
        public Nullable<int> betalactamicos { get; set; }
        public Nullable<int> sulfasimas { get; set; }
        public Nullable<int> tetraciclina { get; set; }
        public Nullable<int> alcohol_75 { get; set; }
        public Nullable<int> aflatoxinas { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_d_fichas C_envios_leche_d_fichas { get; set; }
    }
}
