//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_clientes()
        {
            this.C_envios_leche_cliente_destinos = new HashSet<C_envios_leche_cliente_destinos>();
            this.C_envios_leche_programacion_semanal_cliente_d = new HashSet<C_envios_leche_programacion_semanal_cliente_d>();
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
            this.C_envios_leche_cumplimiento_mensual = new HashSet<C_envios_leche_cumplimiento_mensual>();
        }
    
        public int id_envio_leche_cliente_ms { get; set; }
        public string nombre_comercial { get; set; }
        public string razon_social { get; set; }
        public Nullable<int> id_condicion_pago { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public string cuenta_cxc { get; set; }
        public Nullable<int> id_cliente_microsip { get; set; }
        public string RFC { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cliente_destinos> C_envios_leche_cliente_destinos { get; set; }
        public virtual C_tipos_moneda C_tipos_moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d> C_envios_leche_programacion_semanal_cliente_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_mensual> C_envios_leche_cumplimiento_mensual { get; set; }
    }
}
