//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_lote_d
    {
        public int id_envio_leche_lote_d { get; set; }
        public Nullable<int> id_envio_leche_lote_g { get; set; }
        public Nullable<int> id_envio_leche_confirmacion { get; set; }
        public Nullable<decimal> precio_leche { get; set; }
        public Nullable<decimal> precio_flete { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_lote_g C_envios_leche_lote_g { get; set; }
        public virtual C_envios_leche_confirmacion C_envios_leche_confirmacion { get; set; }
    }
}
