//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_g()
        {
            this.C_envios_leche_confirmacion = new HashSet<C_envios_leche_confirmacion>();
            this.C_envios_leche_d_fichas = new HashSet<C_envios_leche_d_fichas>();
        }
    
        public int id_envio_leche_g { get; set; }
        public Nullable<int> id_tipo_tanque_pipa { get; set; }
        public Nullable<int> id_establo_envio { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_envio_leche_status { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<int> id_envio_leche_cliente_ms { get; set; }
        public Nullable<int> id_destino_envio_leche { get; set; }
        public Nullable<int> id_producto_envio { get; set; }
        public string folio { get; set; }
        public string remision_cliente { get; set; }
        public string operador { get; set; }
        public Nullable<int> id_linea_transportista { get; set; }
        public string placas { get; set; }
        public Nullable<decimal> kilos_totales { get; set; }
        public Nullable<decimal> litros_totales { get; set; }
        public Nullable<decimal> densidad_total { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_bascula_lineas_transportistas C_bascula_lineas_transportistas { get; set; }
        public virtual C_envios_leche_clientes C_envios_leche_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_confirmacion> C_envios_leche_confirmacion { get; set; }
        public virtual C_envios_leche_destinos C_envios_leche_destinos { get; set; }
        public virtual C_envios_leche_tipos_tanques C_envios_leche_tipos_tanques { get; set; }
        public virtual C_establos C_establos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_envios_leche_status C_envios_leche_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_d_fichas> C_envios_leche_d_fichas { get; set; }
    }
}
