//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_cumplimiento_mensual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_cumplimiento_mensual()
        {
            this.C_envios_leche_cumplimiento_semanal = new HashSet<C_envios_leche_cumplimiento_semanal>();
        }
    
        public int id_cumplimiento_mensual { get; set; }
        public Nullable<int> id_envio_leche_cliente_ms { get; set; }
        public Nullable<int> id_anio_presupuesto { get; set; }
        public Nullable<int> id_mes_presupuesto { get; set; }
        public Nullable<decimal> litros_totales { get; set; }
        public Nullable<decimal> litros_dia { get; set; }
        public Nullable<decimal> full_semana { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_clientes C_envios_leche_clientes { get; set; }
        public virtual C_presupuestos_anios C_presupuestos_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_semanal> C_envios_leche_cumplimiento_semanal { get; set; }
        public virtual C_presupuestos_meses C_presupuestos_meses { get; set; }
    }
}
