//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_programacion_diaria_d
    {
        public int id_programacion_diaria_d { get; set; }
        public Nullable<int> id_programacion_diaria_g { get; set; }
        public Nullable<int> id_dia_presupuesto { get; set; }
        public System.DateTime fecha_dia { get; set; }
        public Nullable<decimal> produccion { get; set; }
        public Nullable<decimal> sobrante { get; set; }
        public Nullable<decimal> faltante { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_presupuestos_dias C_presupuestos_dias { get; set; }
        public virtual C_envios_leche_programacion_diaria_g C_envios_leche_programacion_diaria_g { get; set; }
    }
}
