//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_envios_leche_programacion_semanal_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_envios_leche_programacion_semanal_g()
        {
            this.C_envios_leche_programacion_semanal_cliente_d = new HashSet<C_envios_leche_programacion_semanal_cliente_d>();
            this.C_envios_leche_programacion_semanal_cliente_d_dias = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias>();
        }
    
        public int id_programacion_semanal_g { get; set; }
        public Nullable<int> id_programacion_diaria_g { get; set; }
        public Nullable<int> no_semana { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> id_anio { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_envios_leche_programacion_diaria_g C_envios_leche_programacion_diaria_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d> C_envios_leche_programacion_semanal_cliente_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias> C_envios_leche_programacion_semanal_cliente_d_dias { get; set; }
        public virtual C_presupuestos_anios C_presupuestos_anios { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
