//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_logs_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_establos_caseta_logs_g()
        {
            this.C_establos_caseta_logs_d_visita_general = new HashSet<C_establos_caseta_logs_d_visita_general>();
            this.C_establos_caseta_logs_d_visita_taller = new HashSet<C_establos_caseta_logs_d_visita_taller>();
        }
    
        public int id_caseta_log_g { get; set; }
        public Nullable<int> id_establo { get; set; }
        public string nombre_registro { get; set; }
        public string asunto { get; set; }
        public string placas { get; set; }
        public Nullable<int> id_tipo_entrada_caseta { get; set; }
        public Nullable<int> id_caseta_area { get; set; }
        public Nullable<System.DateTime> fecha_entrada { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<decimal> tiempo_estancia { get; set; }
        public Nullable<int> id_usuario_registra_entrada { get; set; }
        public Nullable<int> id_usuario_registra_salida { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_establos C_establos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_d_visita_general> C_establos_caseta_logs_d_visita_general { get; set; }
        public virtual C_establos_caseta_tipos_entradas C_establos_caseta_tipos_entradas { get; set; }
        public virtual C_establos_caseta_tipos_entradas_areas C_establos_caseta_tipos_entradas_areas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_d_visita_taller> C_establos_caseta_logs_d_visita_taller { get; set; }
    }
}
