//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_tipos_entradas_areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_establos_caseta_tipos_entradas_areas()
        {
            this.C_establos_caseta_logs_g = new HashSet<C_establos_caseta_logs_g>();
            this.C_establos_caseta_vales_salida = new HashSet<C_establos_caseta_vales_salida>();
        }
    
        public int id_caseta_area { get; set; }
        public Nullable<int> id_area_establo { get; set; }
        public string nombre_area { get; set; }
        public Nullable<int> id_tipo_entrada_caseta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_establos_areas C_establos_areas { get; set; }
        public virtual C_establos_caseta_tipos_entradas C_establos_caseta_tipos_entradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_g> C_establos_caseta_logs_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_vales_salida> C_establos_caseta_vales_salida { get; set; }
    }
}
