//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_logs_d_visita_taller
    {
        public int id_caseta_vale_log { get; set; }
        public Nullable<int> id_caseta_log_g { get; set; }
        public Nullable<int> id_caseta_vale { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registro { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_establos_caseta_logs_g C_establos_caseta_logs_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_establos_caseta_vales_salida C_establos_caseta_vales_salida { get; set; }
    }
}
