//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_vales_salida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_establos_caseta_vales_salida()
        {
            this.C_establos_caseta_logs_d_visita_taller = new HashSet<C_establos_caseta_logs_d_visita_taller>();
        }
    
        public int id_caseta_vale { get; set; }
        public Nullable<int> id_establo { get; set; }
        public string folio { get; set; }
        public Nullable<int> id_area { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_caseta_tipo_salida { get; set; }
        public string tipo_salida { get; set; }
        public Nullable<bool> registrado { get; set; }
        public string proveedor { get; set; }
        public string nombre_activo { get; set; }
        public string id_activo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_establos C_establos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_d_visita_taller> C_establos_caseta_logs_d_visita_taller { get; set; }
        public virtual C_establos_caseta_tipos_entradas_areas C_establos_caseta_tipos_entradas_areas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_establos_caseta_vales_tipos_salidas C_establos_caseta_vales_tipos_salidas { get; set; }
    }
}
