//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_bastones
    {
        public int ID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Vaca { get; set; }
        public Nullable<long> IDPasivo { get; set; }
        public string Estado { get; set; }
        public string EstadoGinecologico { get; set; }
        public Nullable<decimal> Edad { get; set; }
    }
}
