//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_logs_d_visita_general
    {
        public int id_caseta_log_d_visita_general { get; set; }
        public Nullable<int> id_caseta_log_g { get; set; }
        public string observaciones { get; set; }
    
        public virtual C_establos_caseta_logs_g C_establos_caseta_logs_g { get; set; }
    }
}
