//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_establos_equipos()
        {
            this.C_almacen_solicitudes_mercancia_g = new HashSet<C_almacen_solicitudes_mercancia_g>();
        }
    
        public int id_establo_equipo { get; set; }
        public string clave_equipo { get; set; }
        public string nombre_equipo { get; set; }
        public string tipo { get; set; }
        public string area { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g { get; set; }
    }
}
