//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_establos_caseta_vales_tipos_salidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_establos_caseta_vales_tipos_salidas()
        {
            this.C_establos_caseta_vales_salida = new HashSet<C_establos_caseta_vales_salida>();
        }
    
        public int id_caseta_tipo_salida { get; set; }
        public string nombre_tipo_salida { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_vales_salida> C_establos_caseta_vales_salida { get; set; }
    }
}
