//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_evaluaciones_departamentos()
        {
            this.C_evaluaciones_departamentos_empleados = new HashSet<C_evaluaciones_departamentos_empleados>();
            this.C_evaluaciones_departamentos_rubros = new HashSet<C_evaluaciones_departamentos_rubros>();
            this.C_evaluaciones_departamentos_usuarios = new HashSet<C_evaluaciones_departamentos_usuarios>();
            this.C_evaluaciones_d_empleados = new HashSet<C_evaluaciones_d_empleados>();
        }
    
        public int id_evaluacion_departamento { get; set; }
        public string nombre_departamento { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_departamentos_empleados> C_evaluaciones_departamentos_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_departamentos_rubros> C_evaluaciones_departamentos_rubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_departamentos_usuarios> C_evaluaciones_departamentos_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_empleados> C_evaluaciones_d_empleados { get; set; }
    }
}
