//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_conceptos_rubros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_evaluaciones_conceptos_rubros()
        {
            this.C_evaluaciones_d_conceptos = new HashSet<C_evaluaciones_d_conceptos>();
        }
    
        public int id_evaluacion_concepto_rubro { get; set; }
        public string nombre_concepto { get; set; }
        public Nullable<int> id_evaluacion_rubro { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_evaluaciones_rubros C_evaluaciones_rubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_conceptos> C_evaluaciones_d_conceptos { get; set; }
    }
}
