//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_evaluaciones_g()
        {
            this.C_evaluaciones_d_empleados = new HashSet<C_evaluaciones_d_empleados>();
            this.C_evaluaciones_d_conceptos = new HashSet<C_evaluaciones_d_conceptos>();
            this.C_evaluaciones_d_calificaciones = new HashSet<C_evaluaciones_d_calificaciones>();
        }
    
        public int id_evaluacion_g { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_anio { get; set; }
        public Nullable<bool> abierta_cerrada { get; set; }
        public Nullable<System.DateTime> fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_presupuestos_anios C_presupuestos_anios { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_empleados> C_evaluaciones_d_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_conceptos> C_evaluaciones_d_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_calificaciones> C_evaluaciones_d_calificaciones { get; set; }
    }
}
