//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_d_conceptos
    {
        public int id_evaluacion_d_concepto { get; set; }
        public Nullable<int> id_evaluacion_d_empleado { get; set; }
        public Nullable<int> id_evaluacion_g { get; set; }
        public Nullable<int> id_evaluacion_concepto_rubro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<decimal> porcentaje_calificacion { get; set; }
        public Nullable<decimal> calificacion { get; set; }
        public Nullable<int> id_evaluacion_status { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_evaluaciones_conceptos_rubros C_evaluaciones_conceptos_rubros { get; set; }
        public virtual C_evaluaciones_d_empleados C_evaluaciones_d_empleados { get; set; }
        public virtual C_evaluaciones_g C_evaluaciones_g { get; set; }
        public virtual C_evaluaciones_status C_evaluaciones_status { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
