//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_departamentos_empleados
    {
        public int id_evaluacion_departamento_empleado { get; set; }
        public Nullable<int> id_evaluacion_departamento { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_evaluaciones_departamentos C_evaluaciones_departamentos { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
    }
}
