//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_evaluaciones_d_empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_evaluaciones_d_empleados()
        {
            this.C_evaluaciones_d_conceptos = new HashSet<C_evaluaciones_d_conceptos>();
            this.C_evaluaciones_d_calificaciones = new HashSet<C_evaluaciones_d_calificaciones>();
        }
    
        public int id_evaluacion_d_empleado { get; set; }
        public Nullable<int> id_evaluacion_g { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<decimal> calificacion_final { get; set; }
        public Nullable<int> id_usuario_califica { get; set; }
        public Nullable<int> id_evaluacion_status { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_evaluaciones_departamentos C_evaluaciones_departamentos { get; set; }
        public virtual C_evaluaciones_g C_evaluaciones_g { get; set; }
        public virtual C_evaluaciones_status C_evaluaciones_status { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_conceptos> C_evaluaciones_d_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_calificaciones> C_evaluaciones_d_calificaciones { get; set; }
    }
}
