//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_firmas_usuarios
    {
        public int id_firmas_usuario { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public Nullable<int> id_cargo_contable_g { get; set; }
        public Nullable<int> id_firma_cargo_permiso { get; set; }
    
        public virtual C_cargos_contables_g C_cargos_contables_g { get; set; }
        public virtual C_firmas_cargo_permisos C_firmas_cargo_permisos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
