//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_firmas_usuarios_montos
    {
        public int id_usuario_montos { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public Nullable<double> montos { get; set; }
        public Nullable<System.DateTime> fecha_registros { get; set; }
        public Nullable<System.DateTime> fecha_actualizacions { get; set; }
        public Nullable<bool> monto_ilimitados { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
