//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_mov_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_inventario_almacen_mov_g()
        {
            this.C_inventario_almacen_mov_d = new HashSet<C_inventario_almacen_mov_d>();
            this.C_inventario_almacen_mov_d_recepciones_logs = new HashSet<C_inventario_almacen_mov_d_recepciones_logs>();
        }
    
        public int id_inventario_almacen_mov_g { get; set; }
        public Nullable<int> id_almacen_origen { get; set; }
        public Nullable<int> id_almacen_destino { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_inventario_mov_tipo { get; set; }
        public string descripcion_mov { get; set; }
        public Nullable<int> id_inventario_mov_status { get; set; }
        public Nullable<int> id_transaccion_orden_g { get; set; }
        public Nullable<int> id_transaccion_solicitud_mercancia_g { get; set; }
        public Nullable<bool> remision_factura { get; set; }
        public string folio_remi_fact { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g1 { get; set; }
        public virtual C_almacen_solicitudes_mercancia_g C_almacen_solicitudes_mercancia_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d> C_inventario_almacen_mov_d { get; set; }
        public virtual C_inventario_mov_status C_inventario_mov_status { get; set; }
        public virtual C_inventario_mov_tipos C_inventario_mov_tipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_compras_ordenes_g C_compras_ordenes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d_recepciones_logs> C_inventario_almacen_mov_d_recepciones_logs { get; set; }
    }
}
