//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_mov_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_inventario_mov_status()
        {
            this.C_inventario_almacen_mov_d = new HashSet<C_inventario_almacen_mov_d>();
            this.C_inventario_almacen_mov_g = new HashSet<C_inventario_almacen_mov_g>();
        }
    
        public int id_inventario_mov_status { get; set; }
        public string nombre_status { get; set; }
        public string color { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d> C_inventario_almacen_mov_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_g> C_inventario_almacen_mov_g { get; set; }
    }
}
