//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_mov_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_inventario_almacen_mov_d()
        {
            this.C_inventario_almacen_ajustes_d = new HashSet<C_inventario_almacen_ajustes_d>();
            this.C_inventario_almacen_mov_d_recepciones_logs = new HashSet<C_inventario_almacen_mov_d_recepciones_logs>();
        }
    
        public int id_inventario_almacen_mov_d { get; set; }
        public Nullable<int> id_inventario_almacen_mov_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> entrada_salida { get; set; }
        public Nullable<int> id_almacen_g { get; set; }
        public Nullable<int> id_inventario_mov_status { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_inventario_mov_status C_inventario_mov_status { get; set; }
        public virtual C_inventario_almacen_mov_g C_inventario_almacen_mov_g { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_ajustes_d> C_inventario_almacen_ajustes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d_recepciones_logs> C_inventario_almacen_mov_d_recepciones_logs { get; set; }
    }
}
