//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_devoluciones_d
    {
        public int id_inventario_devolucion_d { get; set; }
        public Nullable<int> id_inventario_devolucion_g { get; set; }
        public Nullable<int> id_solicitud_mercancia_d { get; set; }
        public Nullable<int> id_solicitud_mercancia_d_log { get; set; }
        public Nullable<decimal> cantidad_original { get; set; }
        public Nullable<decimal> cantidad_devuelta { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_almacen_solicitudes_mercancia_d C_almacen_solicitudes_mercancia_d { get; set; }
        public virtual C_almacen_solicitudes_mercancia_d_logs C_almacen_solicitudes_mercancia_d_logs { get; set; }
        public virtual C_inventario_almacen_devoluciones_g C_inventario_almacen_devoluciones_g { get; set; }
    }
}
