//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_captura_d
    {
        public int id_inventario_d { get; set; }
        public Nullable<int> id_inventario_g { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<decimal> cantidad_captura { get; set; }
        public Nullable<decimal> cantidad_sistema { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_inventario_almacen_captura_g C_inventario_almacen_captura_g { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
    }
}
