//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacenes_articulos
    {
        public int id_articulo_almacen { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_ubicacion_almacen { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_almacen_ubicaciones_articulos C_almacen_ubicaciones_articulos { get; set; }
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
    }
}
