//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_mov_d_recepciones_logs
    {
        public int id_almacen_mov_d_recepciones_logs { get; set; }
        public Nullable<int> id_inventario_almacen_mov_g { get; set; }
        public Nullable<int> id_inventario_almacen_mov_d { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public string folio_remision_factura { get; set; }
        public Nullable<int> id_usuario_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<decimal> cantidad_recepcion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_articulos_catalogo C_articulos_catalogo { get; set; }
        public virtual C_inventario_almacen_mov_d C_inventario_almacen_mov_d { get; set; }
        public virtual C_inventario_almacen_mov_g C_inventario_almacen_mov_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
