//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_inventario_almacen_captura_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_inventario_almacen_captura_g()
        {
            this.C_inventario_almacen_captura_d = new HashSet<C_inventario_almacen_captura_d>();
        }
    
        public int id_inventario_g { get; set; }
        public Nullable<int> id_almacen { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_tipo_inventario { get; set; }
        public Nullable<int> id_status_inventario { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_tipo_articulos_inventario { get; set; }
    
        public virtual C_almacen_almacenes_g C_almacen_almacenes_g { get; set; }
        public virtual C_articulos_tipos C_articulos_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_captura_d> C_inventario_almacen_captura_d { get; set; }
        public virtual C_inventario_status C_inventario_status { get; set; }
        public virtual C_inventario_tipos C_inventario_tipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
