//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_logs_procesos
    {
        public int id_log { get; set; }
        public Nullable<int> id_tipo_log { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string msj { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_logs_procesos_tipos C_logs_procesos_tipos { get; set; }
    }
}
