//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_logs_sesiones_diarias
    {
        public int id_log_siib { get; set; }
        public Nullable<System.DateTime> dia_sesion { get; set; }
        public Nullable<int> usuarios_conectados { get; set; }
    }
}
