//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_logs_correos_enviados
    {
        public int log_correo { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string IP { get; set; }
        public Nullable<int> id_usuario { get; set; }
    }
}
