//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_modulos_sub_permisos_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_modulos_sub_permisos_usuarios()
        {
            this.C_modulos_sub_permisos_usuarios_asignados = new HashSet<C_modulos_sub_permisos_usuarios_asignados>();
        }
    
        public int id_submodulo_permiso_usuario { get; set; }
        public Nullable<int> id_submodulo { get; set; }
        public string nombre_permiso { get; set; }
        public string descripcion_permiso { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_modulos_sub_permisos_usuarios_asignados> C_modulos_sub_permisos_usuarios_asignados { get; set; }
        public virtual C_modulos_sub C_modulos_sub { get; set; }
    }
}
