//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_incidencias
    {
        public int id_incidencia_nomina { get; set; }
        public Nullable<int> Empleado_id { get; set; }
        public Nullable<int> Reg_patronal_id { get; set; }
        public Nullable<int> Nuevo_Reg_patronal_id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Salario_diario { get; set; }
        public Nullable<decimal> Salario_hora { get; set; }
        public Nullable<decimal> Salario_integ { get; set; }
        public Nullable<decimal> Pctje_integ { get; set; }
        public Nullable<int> id_tipo_incidencia { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_usuario_registro { get; set; }
        public Nullable<int> id_puesto_actual { get; set; }
        public Nullable<int> id_puesto_nuevo { get; set; }
        public Nullable<int> id_departamento_actual { get; set; }
        public Nullable<int> id_departamento_nuevo { get; set; }
        public Nullable<decimal> Salario_diario_nuevo { get; set; }
        public Nullable<decimal> Salario_hora_nuevo { get; set; }
        public Nullable<decimal> Salario_integ_nuevo { get; set; }
        public Nullable<bool> Lista_negra { get; set; }
    
        public virtual C_nomina_departamentos C_nomina_departamentos { get; set; }
        public virtual C_nomina_departamentos C_nomina_departamentos1 { get; set; }
        public virtual C_nomina_incidencias_tipos C_nomina_incidencias_tipos { get; set; }
        public virtual C_nomina_regimen_patronal C_nomina_regimen_patronal { get; set; }
        public virtual C_nomina_regimen_patronal C_nomina_regimen_patronal1 { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        public virtual C_nomina_puestos C_nomina_puestos { get; set; }
        public virtual C_nomina_puestos C_nomina_puestos1 { get; set; }
    }
}
