//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_parametros_porcentajes_integracion
    {
        public int id_nomina_parametro_porcentaje_integracion { get; set; }
        public Nullable<int> tiempo_minimo { get; set; }
        public Nullable<int> tipo_maximo { get; set; }
        public Nullable<decimal> porcentaje_prima_vacacacional { get; set; }
        public Nullable<int> aguinaldo { get; set; }
        public Nullable<decimal> porcentaje_integracion { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
