//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_checador_hrs_extras_estimulos
    {
        public int id_nomina_checador_hrs_extra_estimulo { get; set; }
        public Nullable<int> Empleado_id { get; set; }
        public Nullable<System.DateTime> fecha_accion { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> pagar_hrs { get; set; }
        public Nullable<int> hrs_extra_no { get; set; }
        public Nullable<decimal> hrs_extra_monto { get; set; }
        public Nullable<bool> pagar_extimulo { get; set; }
        public Nullable<decimal> estimulo_extra_monto { get; set; }
        public Nullable<int> estimulo_extra_no { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
