//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_empleados_solicitudes
    {
        public int id_empleado_solicitud { get; set; }
        public Nullable<int> id_empleado_solicitud_status { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string path { get; set; }
        public string Nombre_completo { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public string Nombres { get; set; }
        public string Regimen { get; set; }
        public Nullable<int> Puesto_no_id { get; set; }
        public Nullable<int> Depto_no_id { get; set; }
        public Nullable<int> Frepag_id { get; set; }
        public Nullable<int> Reg_patronal_id { get; set; }
        public Nullable<bool> Es_jefe { get; set; }
        public string Forma_pago { get; set; }
        public string Contrato { get; set; }
        public string Dias_hrs_jsr { get; set; }
        public string Turno { get; set; }
        public Nullable<decimal> Jornada { get; set; }
        public Nullable<int> Regimen_fiscal { get; set; }
        public string Contrato_sat { get; set; }
        public string Jornada_sat { get; set; }
        public string Es_sindicalizado { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public string Estatus { get; set; }
        public string Zona_salmin { get; set; }
        public Nullable<int> Tabla_antig_id { get; set; }
        public Nullable<int> Tipo_salario { get; set; }
        public Nullable<decimal> Pctje_integ { get; set; }
        public Nullable<decimal> Salario_diario { get; set; }
        public Nullable<decimal> Salario_hora { get; set; }
        public Nullable<decimal> Salario_integ { get; set; }
        public Nullable<bool> Es_dir_admr_gte_gral { get; set; }
        public Nullable<bool> PTU { get; set; }
        public Nullable<bool> IMSS { get; set; }
        public Nullable<bool> CAS { get; set; }
        public Nullable<bool> Pensionado { get; set; }
        public Nullable<bool> Deshab_imptos { get; set; }
        public Nullable<bool> Calc_isr_anual { get; set; }
        public string Calle { get; set; }
        public string Nombre_calle { get; set; }
        public string Num_exterior { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> Ciudad_id { get; set; }
        public string Codigo_postal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public Nullable<int> Ciudad_nacimiento_id { get; set; }
        public string Estado_civil { get; set; }
        public Nullable<short> Num_hijos { get; set; }
        public string Nombre_padre { get; set; }
        public string Nombre_madre { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string Reg_imss { get; set; }
        public Nullable<int> Grupo_pago_elect_id { get; set; }
        public string Tipo_ctaban_pago_elect { get; set; }
        public string Num_ctaban_pago_elect { get; set; }
        public string Usuario_creador { get; set; }
        public Nullable<System.DateTime> Fecha_hora_creacion { get; set; }
        public Nullable<decimal> Salario_diario_establo { get; set; }
        public Nullable<decimal> Salario_hora_establo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_usuario_valida { get; set; }
        public Nullable<System.DateTime> fecha_valida { get; set; }
        public Nullable<int> id_usuario_autoriza { get; set; }
        public Nullable<System.DateTime> fecha_autoriza { get; set; }
    
        public virtual C_direcciones_ciudades C_direcciones_ciudades { get; set; }
        public virtual C_direcciones_ciudades C_direcciones_ciudades1 { get; set; }
        public virtual C_nomina_contrato C_nomina_contrato { get; set; }
        public virtual C_nomina_departamentos C_nomina_departamentos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        public virtual C_nomina_empleados_solicitudes_status C_nomina_empleados_solicitudes_status { get; set; }
        public virtual C_nomina_estado_civil C_nomina_estado_civil { get; set; }
        public virtual C_nomina_frecuencias_pagos C_nomina_frecuencias_pagos { get; set; }
        public virtual C_nomina_forma_pago C_nomina_forma_pago { get; set; }
        public virtual C_nomina_grupos_pagos C_nomina_grupos_pagos { get; set; }
        public virtual C_nomina_regimen_patronal C_nomina_regimen_patronal { get; set; }
        public virtual C_nomina_tipo_cuenta_bancaria C_nomina_tipo_cuenta_bancaria { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo2 { get; set; }
        public virtual C_nomina_puestos C_nomina_puestos { get; set; }
    }
}
