//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_beta_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_beta_g()
        {
            this.C_nomina_beta_d_areas = new HashSet<C_nomina_beta_d_areas>();
            this.C_nomina_beta_d_areas_empleados = new HashSet<C_nomina_beta_d_areas_empleados>();
            this.C_nomina_beta_d_areas_empleados_conceptos = new HashSet<C_nomina_beta_d_areas_empleados_conceptos>();
        }
    
        public int id_nomina_g { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<int> id_anio { get; set; }
        public Nullable<int> no_semana { get; set; }
        public string nombre_nomina { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_usuario_creador { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> id_nomina_status { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<int> id_usuario_cierre { get; set; }
    
        public virtual C_establos C_establos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas> C_nomina_beta_d_areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados> C_nomina_beta_d_areas_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados_conceptos> C_nomina_beta_d_areas_empleados_conceptos { get; set; }
        public virtual C_nomina_status C_nomina_status { get; set; }
        public virtual C_presupuestos_anios C_presupuestos_anios { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
    }
}
