//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_beta_d_areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_beta_d_areas()
        {
            this.C_nomina_beta_d_areas_empleados = new HashSet<C_nomina_beta_d_areas_empleados>();
        }
    
        public int id_nomina_d_area { get; set; }
        public Nullable<int> id_nomina_g { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<int> no_empleados { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_departamentos C_nomina_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados> C_nomina_beta_d_areas_empleados { get; set; }
        public virtual C_nomina_beta_g C_nomina_beta_g { get; set; }
    }
}
