//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_empleados()
        {
            this.C_nomina_beta_d_areas_empleados = new HashSet<C_nomina_beta_d_areas_empleados>();
            this.C_nomina_empleados_checador = new HashSet<C_nomina_empleados_checador>();
            this.C_nomina_inasistencias = new HashSet<C_nomina_inasistencias>();
            this.C_nomina_incidencias = new HashSet<C_nomina_incidencias>();
            this.C_evaluaciones_departamentos_empleados = new HashSet<C_evaluaciones_departamentos_empleados>();
            this.C_evaluaciones_empleados_bonos = new HashSet<C_evaluaciones_empleados_bonos>();
            this.C_evaluaciones_d_empleados = new HashSet<C_evaluaciones_d_empleados>();
            this.C_almacen_solicitudes_mercancia_g = new HashSet<C_almacen_solicitudes_mercancia_g>();
            this.C_nomina_checador_prenomina = new HashSet<C_nomina_checador_prenomina>();
            this.C_nomina_checador_hrs_extras_estimulos = new HashSet<C_nomina_checador_hrs_extras_estimulos>();
            this.C_compras_ordenes_precarga_g = new HashSet<C_compras_ordenes_precarga_g>();
        }
    
        public int Empleado_id { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Nombre_completo { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public string Nombres { get; set; }
        public string Regimen { get; set; }
        public Nullable<int> Puesto_no_id { get; set; }
        public Nullable<int> Depto_no_id { get; set; }
        public Nullable<int> Frepag_id { get; set; }
        public Nullable<int> Reg_patronal_id { get; set; }
        public Nullable<bool> Es_jefe { get; set; }
        public string Forma_pago { get; set; }
        public string Contrato { get; set; }
        public string Dias_hrs_jsr { get; set; }
        public string Turno { get; set; }
        public Nullable<decimal> Jornada { get; set; }
        public Nullable<int> Regimen_fiscal { get; set; }
        public string Contrato_sat { get; set; }
        public string Jornada_sat { get; set; }
        public string Es_sindicalizado { get; set; }
        public Nullable<System.DateTime> Fecha_ingreso { get; set; }
        public string Estatus { get; set; }
        public string Zona_salmin { get; set; }
        public Nullable<int> Tabla_antig_id { get; set; }
        public Nullable<int> Tipo_salario { get; set; }
        public Nullable<decimal> Pctje_integ { get; set; }
        public Nullable<decimal> Salario_diario { get; set; }
        public Nullable<decimal> Salario_hora { get; set; }
        public Nullable<decimal> Salario_integ { get; set; }
        public Nullable<bool> Es_dir_admr_gte_gral { get; set; }
        public Nullable<bool> PTU { get; set; }
        public Nullable<bool> IMSS { get; set; }
        public Nullable<bool> CAS { get; set; }
        public Nullable<bool> Pensionado { get; set; }
        public Nullable<bool> Deshab_imptos { get; set; }
        public Nullable<bool> Calc_isr_anual { get; set; }
        public string Calle { get; set; }
        public string Nombre_calle { get; set; }
        public string Num_exterior { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> Ciudad_id { get; set; }
        public string Codigo_postal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public Nullable<int> Ciudad_nacimiento_id { get; set; }
        public string Estado_civil { get; set; }
        public Nullable<short> Num_hijos { get; set; }
        public string Nombre_padre { get; set; }
        public string Nombre_madre { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string Reg_imss { get; set; }
        public Nullable<int> Grupo_pago_elect_id { get; set; }
        public string Tipo_ctaban_pago_elect { get; set; }
        public string Num_ctaban_pago_elect { get; set; }
        public string Usuario_creador { get; set; }
        public Nullable<System.DateTime> Fecha_hora_creacion { get; set; }
        public Nullable<decimal> Salario_diario_establo { get; set; }
        public Nullable<decimal> Salario_hora_establo { get; set; }
        public string Path_constancia_fiscal { get; set; }
        public Nullable<bool> Lista_negra { get; set; }
        public Nullable<int> id_formacion_academica_g { get; set; }
    
        public virtual C_direcciones_ciudades C_direcciones_ciudades { get; set; }
        public virtual C_direcciones_ciudades C_direcciones_ciudades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados> C_nomina_beta_d_areas_empleados { get; set; }
        public virtual C_nomina_contrato C_nomina_contrato { get; set; }
        public virtual C_nomina_departamentos C_nomina_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_checador> C_nomina_empleados_checador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_inasistencias> C_nomina_inasistencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias { get; set; }
        public virtual C_nomina_estado_civil C_nomina_estado_civil { get; set; }
        public virtual C_nomina_forma_pago C_nomina_forma_pago { get; set; }
        public virtual C_nomina_frecuencias_pagos C_nomina_frecuencias_pagos { get; set; }
        public virtual C_nomina_grupos_pagos C_nomina_grupos_pagos { get; set; }
        public virtual C_nomina_puestos C_nomina_puestos { get; set; }
        public virtual C_nomina_regimen_patronal C_nomina_regimen_patronal { get; set; }
        public virtual C_nomina_tipo_cuenta_bancaria C_nomina_tipo_cuenta_bancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_departamentos_empleados> C_evaluaciones_departamentos_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_empleados_bonos> C_evaluaciones_empleados_bonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_empleados> C_evaluaciones_d_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_prenomina> C_nomina_checador_prenomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_hrs_extras_estimulos> C_nomina_checador_hrs_extras_estimulos { get; set; }
        public virtual C_rh_formacion_academica_g C_rh_formacion_academica_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_g> C_compras_ordenes_precarga_g { get; set; }
    }
}
