//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_checador_conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_checador_conceptos()
        {
            this.C_nomina_checador_prenomina = new HashSet<C_nomina_checador_prenomina>();
            this.C_nomina_checador_prenomina1 = new HashSet<C_nomina_checador_prenomina>();
        }
    
        public int id_nomina_checador_concepto { get; set; }
        public string nombre_concepto { get; set; }
        public string sigla { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_prenomina> C_nomina_checador_prenomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_prenomina> C_nomina_checador_prenomina1 { get; set; }
    }
}
