//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_checador_prenomina
    {
        public int id_nomina_checador_prenomina { get; set; }
        public Nullable<int> Empleado_id { get; set; }
        public Nullable<System.DateTime> fecha_accion { get; set; }
        public Nullable<int> id_nomina_checador_concepto_real { get; set; }
        public Nullable<int> id_nomina_checador_concepto { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_checador_conceptos C_nomina_checador_conceptos { get; set; }
        public virtual C_nomina_checador_conceptos C_nomina_checador_conceptos1 { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
