//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_empleados_checador
    {
        public int id_empleado_nomina_checador { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> Empleado_id { get; set; }
        public Nullable<int> id_empleado_checador { get; set; }
        public Nullable<int> id_usuario_registro_liga { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
    }
}
