//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_regimen_patronal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_regimen_patronal()
        {
            this.C_nomina_empleados_solicitudes = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_incidencias = new HashSet<C_nomina_incidencias>();
            this.C_nomina_incidencias1 = new HashSet<C_nomina_incidencias>();
            this.C_nomina_empleados = new HashSet<C_nomina_empleados>();
        }
    
        public int id_regimen_patronal { get; set; }
        public string numero_regimen_partonal { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> clase_riesgo_sat { get; set; }
        public Nullable<decimal> prima_riesgo { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public Nullable<int> id_tipo_isn { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_tipo_isn C_nomina_tipo_isn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados> C_nomina_empleados { get; set; }
    }
}
