//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_beta_d_areas_empleados_conceptos
    {
        public int id_nomina_empleado_concepto { get; set; }
        public Nullable<int> id_nomina_g { get; set; }
        public Nullable<int> id_nomina_d_area_empleado { get; set; }
        public Nullable<int> id_concepto_nomina { get; set; }
        public string tipo_calculo { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string comentarios { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_beta_d_areas_empleados C_nomina_beta_d_areas_empleados { get; set; }
        public virtual C_nomina_beta_g C_nomina_beta_g { get; set; }
        public virtual C_nomina_conceptos C_nomina_conceptos { get; set; }
    }
}
