//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_cuenta_bancaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_cuenta_bancaria()
        {
            this.C_nomina_grupos_pagos = new HashSet<C_nomina_grupos_pagos>();
        }
    
        public int id_cuenta_bancaria { get; set; }
        public string nombre_cuenta_bancaria { get; set; }
        public Nullable<int> id_banco { get; set; }
        public string numero_cuenta { get; set; }
        public string clabe { get; set; }
        public Nullable<int> id_tipo_cuenta_bancaria { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_grupos_pagos> C_nomina_grupos_pagos { get; set; }
    }
}
