//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_conceptos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_conceptos()
        {
            this.C_nomina_beta_d_areas_empleados_conceptos = new HashSet<C_nomina_beta_d_areas_empleados_conceptos>();
        }
    
        public int id_concepto_nomina { get; set; }
        public string nombre_concepto { get; set; }
        public string nombre_abreviacion { get; set; }
        public string clave_concepto { get; set; }
        public string percepcion_retencion { get; set; }
        public Nullable<int> tipo_sat { get; set; }
        public Nullable<bool> fijo_excepcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> formato_nomina { get; set; }
        public Nullable<bool> calculo_valor_dia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados_conceptos> C_nomina_beta_d_areas_empleados_conceptos { get; set; }
    }
}
