//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_puestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_puestos()
        {
            this.C_nomina_beta_d_areas_empleados = new HashSet<C_nomina_beta_d_areas_empleados>();
            this.C_nomina_empleados = new HashSet<C_nomina_empleados>();
            this.C_nomina_empleados_solicitudes = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_incidencias = new HashSet<C_nomina_incidencias>();
            this.C_nomina_incidencias1 = new HashSet<C_nomina_incidencias>();
        }
    
        public int id_puesto_empleado { get; set; }
        public string nombre_puesto { get; set; }
        public Nullable<decimal> salario_diario { get; set; }
        public Nullable<decimal> salario_diario_max { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados> C_nomina_beta_d_areas_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados> C_nomina_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias1 { get; set; }
    }
}
