//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_grupos_pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_grupos_pagos()
        {
            this.C_nomina_empleados_solicitudes = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_empleados = new HashSet<C_nomina_empleados>();
        }
    
        public int id_grupo_pago { get; set; }
        public string nombre_grupo_pago { get; set; }
        public Nullable<int> id_cuenta_bancaria { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_cuenta_bancaria C_nomina_cuenta_bancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados> C_nomina_empleados { get; set; }
    }
}
