//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_nomina_beta_d_areas_empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_nomina_beta_d_areas_empleados()
        {
            this.C_nomina_beta_d_areas_empleados_conceptos = new HashSet<C_nomina_beta_d_areas_empleados_conceptos>();
        }
    
        public int id_nomina_d_area_empleado { get; set; }
        public Nullable<int> id_nomina_d_area { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<decimal> salario_diario { get; set; }
        public string cuenta_bancaria { get; set; }
        public Nullable<int> id_puesto { get; set; }
        public string nss { get; set; }
        public Nullable<decimal> importe_final { get; set; }
        public Nullable<int> dias_laborados { get; set; }
        public Nullable<int> id_nomina_g { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_beta_d_areas C_nomina_beta_d_areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_d_areas_empleados_conceptos> C_nomina_beta_d_areas_empleados_conceptos { get; set; }
        public virtual C_nomina_beta_g C_nomina_beta_g { get; set; }
        public virtual C_nomina_empleados C_nomina_empleados { get; set; }
        public virtual C_nomina_puestos C_nomina_puestos { get; set; }
    }
}
