//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_parametros_correos_almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_parametros_correos_almacen()
        {
            this.C_almacen_envio_correos_log = new HashSet<C_almacen_envio_correos_log>();
        }
    
        public int id_trigger_correo_almacen { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> ejecutado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_envio_correos_log> C_almacen_envio_correos_log { get; set; }
    }
}
