//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_presupuestos_cuentas_meses_anios
    {
        public int id_presupuesto_area_mes { get; set; }
        public Nullable<int> id_anio { get; set; }
        public Nullable<int> id_mes { get; set; }
        public Nullable<int> id_cuenta_contable_g { get; set; }
        public Nullable<decimal> valor_presupuesto { get; set; }
    
        public virtual C_cuentas_contables_g C_cuentas_contables_g { get; set; }
        public virtual C_presupuestos_anios C_presupuestos_anios { get; set; }
        public virtual C_presupuestos_meses C_presupuestos_meses { get; set; }
    }
}
