//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_presupuestos_meses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_presupuestos_meses()
        {
            this.C_presupuestos_almacenes_cuentas_meses_anios = new HashSet<C_presupuestos_almacenes_cuentas_meses_anios>();
            this.C_presupuestos_cuentas_meses_anios = new HashSet<C_presupuestos_cuentas_meses_anios>();
            this.C_envios_leche_cumplimiento_mensual = new HashSet<C_envios_leche_cumplimiento_mensual>();
        }
    
        public int id_mes_presupuesto { get; set; }
        public string mes { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> no_mes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_almacenes_cuentas_meses_anios> C_presupuestos_almacenes_cuentas_meses_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_cuentas_meses_anios> C_presupuestos_cuentas_meses_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_mensual> C_envios_leche_cumplimiento_mensual { get; set; }
    }
}
