//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_presupuestos_dias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_presupuestos_dias()
        {
            this.C_envios_leche_programacion_diaria_d = new HashSet<C_envios_leche_programacion_diaria_d>();
            this.C_envios_leche_programacion_semanal_cliente_d_dias = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias>();
        }
    
        public int id_dia_presupuesto { get; set; }
        public string dia { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_diaria_d> C_envios_leche_programacion_diaria_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias> C_envios_leche_programacion_semanal_cliente_d_dias { get; set; }
    }
}
