//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_presupuestos_anios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_presupuestos_anios()
        {
            this.C_presupuestos_cuentas_meses_anios = new HashSet<C_presupuestos_cuentas_meses_anios>();
            this.C_presupuestos_almacenes_cuentas_meses_anios = new HashSet<C_presupuestos_almacenes_cuentas_meses_anios>();
            this.C_nomina_beta_g = new HashSet<C_nomina_beta_g>();
            this.C_envios_leche_programacion_diaria_g = new HashSet<C_envios_leche_programacion_diaria_g>();
            this.C_envios_leche_programacion_semanal_g = new HashSet<C_envios_leche_programacion_semanal_g>();
            this.C_evaluaciones_g = new HashSet<C_evaluaciones_g>();
            this.C_envios_leche_cumplimiento_mensual = new HashSet<C_envios_leche_cumplimiento_mensual>();
        }
    
        public int id_anio_presupuesto { get; set; }
        public string anio { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_cuentas_meses_anios> C_presupuestos_cuentas_meses_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_presupuestos_almacenes_cuentas_meses_anios> C_presupuestos_almacenes_cuentas_meses_anios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_g> C_nomina_beta_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_diaria_g> C_envios_leche_programacion_diaria_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_g> C_envios_leche_programacion_semanal_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_g> C_evaluaciones_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_mensual> C_envios_leche_cumplimiento_mensual { get; set; }
    }
}
