//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_rh_formacion_academica_d
    {
        public int id_formacion_academica_d { get; set; }
        public Nullable<int> id_formacion_academica_g { get; set; }
        public Nullable<int> id_formacion_universidad { get; set; }
        public Nullable<int> id_formacion_estudio { get; set; }
        public Nullable<int> id_formacion_status { get; set; }
        public Nullable<int> anio_graduacion { get; set; }
        public Nullable<int> numero_cedula { get; set; }
        public string path_cedula { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_rh_formacion_academica_g C_rh_formacion_academica_g { get; set; }
        public virtual C_rh_formacion_estudio C_rh_formacion_estudio { get; set; }
        public virtual C_rh_formacion_status C_rh_formacion_status { get; set; }
        public virtual C_rh_formacion_universidades C_rh_formacion_universidades { get; set; }
    }
}
