//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_d
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_salida_ganado_d()
        {
            this.C_salida_ganado_logs_d = new HashSet<C_salida_ganado_logs_d>();
        }
    
        public int id_saliga_gan_d { get; set; }
        public Nullable<int> id_salida_gan_g { get; set; }
        public string folio { get; set; }
        public string arete { get; set; }
        public string clasifica { get; set; }
        public string causa_b { get; set; }
        public string cond_ind { get; set; }
        public string edad { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> p_unitario { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> tregistro { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public string sala { get; set; }
        public string path { get; set; }
        public Nullable<int> id_causa_muerte { get; set; }
        public Nullable<bool> confirmado { get; set; }
        public Nullable<int> id_medico { get; set; }
        public string estado { get; set; }
        public string estado_ginecologico { get; set; }
        public Nullable<bool> arete_manual { get; set; }
        public string path_2 { get; set; }
        public string siniiga { get; set; }
    
        public virtual C_salida_ganado_causas_muerte C_salida_ganado_causas_muerte { get; set; }
        public virtual C_salida_ganado_g C_salida_ganado_g { get; set; }
        public virtual C_salida_ganado_medicos C_salida_ganado_medicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_d> C_salida_ganado_logs_d { get; set; }
    }
}
