//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_logs_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_salida_ganado_logs_g()
        {
            this.C_salida_ganado_logs_d = new HashSet<C_salida_ganado_logs_d>();
        }
    
        public int id_salida_gan_logs_g { get; set; }
        public Nullable<int> id_usuario_modifico { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_salida_gan_g { get; set; }
        public string folio { get; set; }
        public string ficha { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ganado { get; set; }
        public string condicion { get; set; }
        public string peso1 { get; set; }
        public string peso2 { get; set; }
        public string peso_t { get; set; }
        public string importe { get; set; }
        public string pesador { get; set; }
        public string chofer { get; set; }
        public string placas { get; set; }
        public string vehiculo { get; set; }
        public string comprador { get; set; }
        public Nullable<bool> cancelada { get; set; }
        public string rstatus { get; set; }
        public Nullable<int> id_tipo_salida { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<int> id_establo { get; set; }
    
        public virtual C_establos C_establos { get; set; }
        public virtual C_salida_ganado_g C_salida_ganado_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_d> C_salida_ganado_logs_d { get; set; }
        public virtual C_salida_ganado_tipos_salidas C_salida_ganado_tipos_salidas { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
    }
}
