//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_condiciones_ganado
    {
        public int id_condicion { get; set; }
        public string condicion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_clasificacion { get; set; }
    
        public virtual C_salida_ganado_clasificaciones_ganado C_salida_ganado_clasificaciones_ganado { get; set; }
    }
}
