//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_medicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_salida_ganado_medicos()
        {
            this.C_salida_ganado_d = new HashSet<C_salida_ganado_d>();
            this.C_salida_ganado_logs_d = new HashSet<C_salida_ganado_logs_d>();
        }
    
        public int id_medico { get; set; }
        public string nombre_medico { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_d> C_salida_ganado_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_d> C_salida_ganado_logs_d { get; set; }
    }
}
