//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_clasificaciones_ganado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_salida_ganado_clasificaciones_ganado()
        {
            this.C_salida_ganado_condiciones_ganado = new HashSet<C_salida_ganado_condiciones_ganado>();
            this.C_salida_ganado_tipos_salidas_clasificaciones = new HashSet<C_salida_ganado_tipos_salidas_clasificaciones>();
        }
    
        public int id_clasificacion_ganado { get; set; }
        public string clasificacion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_condiciones_ganado> C_salida_ganado_condiciones_ganado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_tipos_salidas_clasificaciones> C_salida_ganado_tipos_salidas_clasificaciones { get; set; }
    }
}
