//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_salas
    {
        public int id_sala { get; set; }
        public Nullable<int> id_establo { get; set; }
        public string sala { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_establos C_establos { get; set; }
    }
}
