//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_salida_ganado_tipos_salidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_salida_ganado_tipos_salidas()
        {
            this.C_salida_ganado_tipos_salidas_clasificaciones = new HashSet<C_salida_ganado_tipos_salidas_clasificaciones>();
            this.C_salida_ganado_g = new HashSet<C_salida_ganado_g>();
            this.C_salida_ganado_logs_g = new HashSet<C_salida_ganado_logs_g>();
        }
    
        public int id_tipo_salida_ganado { get; set; }
        public string nombre_salida { get; set; }
        public string color { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_tipos_salidas_clasificaciones> C_salida_ganado_tipos_salidas_clasificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_g> C_salida_ganado_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_g> C_salida_ganado_logs_g { get; set; }
    }
}
