//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sistemas_equipos_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_sistemas_equipos_g()
        {
            this.C_sistemas_equipos_d = new HashSet<C_sistemas_equipos_d>();
            this.C_sistemas_equipos_movs = new HashSet<C_sistemas_equipos_movs>();
        }
    
        public int id_equipo_g { get; set; }
        public Nullable<int> id_usuario_registra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string nombre_equipo { get; set; }
        public Nullable<System.DateTime> fecha_adquisicion { get; set; }
        public string proveedor { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public Nullable<int> id_usuario_actualiza { get; set; }
        public string sku { get; set; }
        public Nullable<int> id_equipo_clasificacion { get; set; }
        public Nullable<bool> nuevo_usado { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_sistemas_equipos_clasificaciones C_sistemas_equipos_clasificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sistemas_equipos_d> C_sistemas_equipos_d { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sistemas_equipos_movs> C_sistemas_equipos_movs { get; set; }
    }
}
