//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sistemas_equipos_movs
    {
        public int id_sistemas_equipo_mov { get; set; }
        public Nullable<int> id_equipo_g { get; set; }
        public Nullable<int> id_tipo_mov { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public Nullable<int> id_usuario_asigna { get; set; }
        public Nullable<int> id_usuario_traspasa { get; set; }
    
        public virtual C_sistemas_equipos_g C_sistemas_equipos_g { get; set; }
    }
}
