//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_sistemas_equipos_d
    {
        public int id_equipo_d { get; set; }
        public Nullable<int> id_equipo_g { get; set; }
        public Nullable<int> id_equipo_caracteristica { get; set; }
        public string valor { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_sistemas_equipos_caracteristicas C_sistemas_equipos_caracteristicas { get; set; }
        public virtual C_sistemas_equipos_g C_sistemas_equipos_g { get; set; }
    }
}
