//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_soporte_tickets_g
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_soporte_tickets_g()
        {
            this.C_soporte_tickets_d = new HashSet<C_soporte_tickets_d>();
        }
    
        public int id_soporte_ticket_g { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_soporte_estado { get; set; }
        public Nullable<int> id_soporte_prioridad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_cierra { get; set; }
        public Nullable<int> id_usuario_solicita { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_soporte_tickets_d> C_soporte_tickets_d { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_soporte_estado C_soporte_estado { get; set; }
        public virtual C_soporte_prioridad C_soporte_prioridad { get; set; }
    }
}
