//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_soporte_tickets_d
    {
        public int id_soporte_ticket_d { get; set; }
        public Nullable<int> id_soporte_ticket_g { get; set; }
        public Nullable<int> id_soporte_categoria { get; set; }
        public Nullable<int> id_soporte_tipo { get; set; }
        public string solicitud { get; set; }
        public Nullable<int> id_soporte_estado { get; set; }
        public Nullable<System.DateTime> fecha_inico { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public Nullable<int> id_usuario_realiza { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_soporte_categorias C_soporte_categorias { get; set; }
        public virtual C_soporte_tickets_g C_soporte_tickets_g { get; set; }
        public virtual C_soporte_tipos C_soporte_tipos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_soporte_estado C_soporte_estado { get; set; }
    }
}
