//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_soporte_tipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_soporte_tipos()
        {
            this.C_soporte_tickets_d = new HashSet<C_soporte_tickets_d>();
        }
    
        public int id_soporte_tipo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_soporte_categoria { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_soporte_categorias C_soporte_categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_soporte_tickets_d> C_soporte_tickets_d { get; set; }
    }
}
