//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_soporte_logs
    {
        public int id_soporte_log { get; set; }
        public Nullable<int> id_usuario_realiza { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string accion_realizada { get; set; }
        public Nullable<bool> activo { get; set; }
        public string justificacion { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
