//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tipos_moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_tipos_moneda()
        {
            this.C_contabilidad_importacion_facturas_d = new HashSet<C_contabilidad_importacion_facturas_d>();
            this.C_envios_leche_clientes = new HashSet<C_envios_leche_clientes>();
            this.C_alimentacion_forrajes_facturas_d = new HashSet<C_alimentacion_forrajes_facturas_d>();
            this.C_alimentacion_forrajes_facturas_g = new HashSet<C_alimentacion_forrajes_facturas_g>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
            this.C_compras_cotizaciones_articulos = new HashSet<C_compras_cotizaciones_articulos>();
            this.C_compras_proveedores = new HashSet<C_compras_proveedores>();
        }
    
        public int id_moneda { get; set; }
        public string nombre { get; set; }
        public string simbolo { get; set; }
        public string clave_fiscal { get; set; }
        public Nullable<bool> moneda_local { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_importacion_facturas_d> C_contabilidad_importacion_facturas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_clientes> C_envios_leche_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_forrajes_facturas_d> C_alimentacion_forrajes_facturas_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_forrajes_facturas_g> C_alimentacion_forrajes_facturas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_articulos> C_compras_cotizaciones_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores> C_compras_proveedores { get; set; }
    }
}
