//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tracker_ingredientes_establos
    {
        public int id_ingrediente { get; set; }
        public string clave { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_establo { get; set; }
        public Nullable<int> id_ing { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_tracker_establos C_tracker_establos { get; set; }
    }
}
