//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tracker_movimientos
    {
        public int id_log_tracker { get; set; }
        public Nullable<System.DateTime> fecha_syync { get; set; }
        public Nullable<int> id_movimiento_tracker { get; set; }
        public Nullable<int> id_carg_desc { get; set; }
        public Nullable<int> id_barch { get; set; }
        public string cve_racion { get; set; }
        public string racion { get; set; }
        public string line_status { get; set; }
        public Nullable<int> id_ing { get; set; }
        public string ing_cve { get; set; }
        public string ing_nombre { get; set; }
        public string ing_tipo { get; set; }
        public Nullable<int> no_animales { get; set; }
        public Nullable<decimal> peso_cargado { get; set; }
        public Nullable<decimal> peso_real { get; set; }
        public Nullable<decimal> diferencia { get; set; }
        public Nullable<int> id_mezclador { get; set; }
        public string nombre_mezclador { get; set; }
        public Nullable<int> id_operador { get; set; }
        public string nombre_operador { get; set; }
        public Nullable<decimal> PMS_P { get; set; }
        public Nullable<decimal> PMS_R { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> sobrante { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_tracker_establo { get; set; }
        public string corral { get; set; }
    
        public virtual C_tracker_establos C_tracker_establos { get; set; }
        public virtual C_tracker_movimientos_tipos C_tracker_movimientos_tipos { get; set; }
    }
}
