//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_unidades_medidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_unidades_medidas()
        {
            this.C_almacen_solicitudes_mercancia_d = new HashSet<C_almacen_solicitudes_mercancia_d>();
            this.C_compras_requi_d = new HashSet<C_compras_requi_d>();
            this.C_articulos_catalogo = new HashSet<C_articulos_catalogo>();
            this.C_compras_ordenes_d = new HashSet<C_compras_ordenes_d>();
            this.C_compras_cotizaciones_articulos = new HashSet<C_compras_cotizaciones_articulos>();
        }
    
        public int id_unidad_medida { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> acepta_decimal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d> C_almacen_solicitudes_mercancia_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_d> C_compras_requi_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_articulos_catalogo> C_articulos_catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_d> C_compras_ordenes_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_articulos> C_compras_cotizaciones_articulos { get; set; }
    }
}
