//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_proveedores
    {
        public int id_usuario_proveedor { get; set; }
        public string usuario_rfc { get; set; }
        public string password { get; set; }
        public Nullable<int> id_compras_proveedor { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> honorario_flete { get; set; }
        public string pass { get; set; }
    
        public virtual C_usuarios_roles C_usuarios_roles { get; set; }
        public virtual C_compras_proveedores C_compras_proveedores { get; set; }
    }
}
