//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_cuentas_contables
    {
        public int id_usuario_cuenta_contable { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_cuenta_contable_g { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_cuentas_contables_g C_cuentas_contables_g { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
