//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_corporativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_usuarios_corporativo()
        {
            this.C_usuarios_establos = new HashSet<C_usuarios_establos>();
            this.C_modulos_sub_permisos_usuarios_asignados = new HashSet<C_modulos_sub_permisos_usuarios_asignados>();
            this.C_almacen_solicitudes_mercancia_g = new HashSet<C_almacen_solicitudes_mercancia_g>();
            this.C_almacen_solicitudes_mercancia_g1 = new HashSet<C_almacen_solicitudes_mercancia_g>();
            this.C_almacen_solicitudes_mercancia_g2 = new HashSet<C_almacen_solicitudes_mercancia_g>();
            this.C_almacen_almacenes_usuarios = new HashSet<C_almacen_almacenes_usuarios>();
            this.C_inventario_almacen_captura_g = new HashSet<C_inventario_almacen_captura_g>();
            this.C_usuarios_centros = new HashSet<C_usuarios_centros>();
            this.C_compras_proveedores_bloqueos = new HashSet<C_compras_proveedores_bloqueos>();
            this.C_firmas_usuarios = new HashSet<C_firmas_usuarios>();
            this.C_firmas_usuarios_montos = new HashSet<C_firmas_usuarios_montos>();
            this.C_almacen_solicitudes_cambios_articulos = new HashSet<C_almacen_solicitudes_cambios_articulos>();
            this.C_compras_requisiciones_links_autorizacion = new HashSet<C_compras_requisiciones_links_autorizacion>();
            this.C_usuarios_masters = new HashSet<C_usuarios_masters>();
            this.C_compras_requi_g = new HashSet<C_compras_requi_g>();
            this.C_compras_requi_g1 = new HashSet<C_compras_requi_g>();
            this.C_compras_requi_g2 = new HashSet<C_compras_requi_g>();
            this.C_compras_requi_g3 = new HashSet<C_compras_requi_g>();
            this.C_compras_requi_g4 = new HashSet<C_compras_requi_g>();
            this.C_compras_requi_g5 = new HashSet<C_compras_requi_g>();
            this.C_inventario_almacen_mov_g = new HashSet<C_inventario_almacen_mov_g>();
            this.C_contabilidad_importacion_facturas_g = new HashSet<C_contabilidad_importacion_facturas_g>();
            this.C_usuarios_cargos_contables = new HashSet<C_usuarios_cargos_contables>();
            this.C_contabilidad_solicitudes_pago_g = new HashSet<C_contabilidad_solicitudes_pago_g>();
            this.C_contabilidad_solicitudes_pago_g1 = new HashSet<C_contabilidad_solicitudes_pago_g>();
            this.C_contabilidad_solicitudes_pago_g2 = new HashSet<C_contabilidad_solicitudes_pago_g>();
            this.C_establos_caseta_logs_g = new HashSet<C_establos_caseta_logs_g>();
            this.C_establos_caseta_logs_g1 = new HashSet<C_establos_caseta_logs_g>();
            this.C_compras_proveedores_portal_tokens = new HashSet<C_compras_proveedores_portal_tokens>();
            this.C_establos_caseta_logs_d_visita_taller = new HashSet<C_establos_caseta_logs_d_visita_taller>();
            this.C_nomina_empleados_checador = new HashSet<C_nomina_empleados_checador>();
            this.C_usuarios_areas_nomina = new HashSet<C_usuarios_areas_nomina>();
            this.C_nomina_inasistencias = new HashSet<C_nomina_inasistencias>();
            this.C_establos_caseta_vales_salida = new HashSet<C_establos_caseta_vales_salida>();
            this.C_almacen_almacenes_ubicaciones_entrega = new HashSet<C_almacen_almacenes_ubicaciones_entrega>();
            this.C_nomina_beta_g = new HashSet<C_nomina_beta_g>();
            this.C_nomina_beta_g1 = new HashSet<C_nomina_beta_g>();
            this.C_compras_requi_g_solicita_autorizacion = new HashSet<C_compras_requi_g_solicita_autorizacion>();
            this.C_alimentacion_productores = new HashSet<C_alimentacion_productores>();
            this.C_nomina_empleados_solicitudes = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_empleados_solicitudes1 = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_empleados_solicitudes2 = new HashSet<C_nomina_empleados_solicitudes>();
            this.C_nomina_incidencias = new HashSet<C_nomina_incidencias>();
            this.C_compras_inversiones_programadas = new HashSet<C_compras_inversiones_programadas>();
            this.C_compras_inversiones_programadas1 = new HashSet<C_compras_inversiones_programadas>();
            this.C_envios_leche_lote_logs = new HashSet<C_envios_leche_lote_logs>();
            this.C_articulos_catalogo_bascula = new HashSet<C_articulos_catalogo_bascula>();
            this.C_envios_leche_cliente_destinos = new HashSet<C_envios_leche_cliente_destinos>();
            this.C_alimentacion_forrajes_facturas_g = new HashSet<C_alimentacion_forrajes_facturas_g>();
            this.C_envios_leche_lote_g = new HashSet<C_envios_leche_lote_g>();
            this.C_alimentacion_articulos_precios = new HashSet<C_alimentacion_articulos_precios>();
            this.C_alimentacion_articulos_precios1 = new HashSet<C_alimentacion_articulos_precios>();
            this.C_envios_leche_precios = new HashSet<C_envios_leche_precios>();
            this.C_envios_leche_precios1 = new HashSet<C_envios_leche_precios>();
            this.C_envios_leche_programacion_diaria_g = new HashSet<C_envios_leche_programacion_diaria_g>();
            this.C_envios_leche_programacion_semanal_g = new HashSet<C_envios_leche_programacion_semanal_g>();
            this.C_alimentacion_programa_g = new HashSet<C_alimentacion_programa_g>();
            this.C_envios_leche_confirmacion = new HashSet<C_envios_leche_confirmacion>();
            this.C_envios_leche_g = new HashSet<C_envios_leche_g>();
            this.C_bascula_fichas = new HashSet<C_bascula_fichas>();
            this.C_alimentacion_dietas_g_comentarios = new HashSet<C_alimentacion_dietas_g_comentarios>();
            this.C_evaluaciones_departamentos_usuarios = new HashSet<C_evaluaciones_departamentos_usuarios>();
            this.C_evaluaciones_empleados_bonos = new HashSet<C_evaluaciones_empleados_bonos>();
            this.C_evaluaciones_empleados_bonos1 = new HashSet<C_evaluaciones_empleados_bonos>();
            this.C_evaluaciones_g = new HashSet<C_evaluaciones_g>();
            this.C_contabilidad_ordenes_pago_g = new HashSet<C_contabilidad_ordenes_pago_g>();
            this.C_evaluaciones_d_empleados = new HashSet<C_evaluaciones_d_empleados>();
            this.C_evaluaciones_d_conceptos = new HashSet<C_evaluaciones_d_conceptos>();
            this.C_inventario_almacen_ajustes_g = new HashSet<C_inventario_almacen_ajustes_g>();
            this.C_envios_leche_cumplimiento_semanal_comentario = new HashSet<C_envios_leche_cumplimiento_semanal_comentario>();
            this.C_compras_requisiciones_logs = new HashSet<C_compras_requisiciones_logs>();
            this.C_compras_ordenes_g = new HashSet<C_compras_ordenes_g>();
            this.C_compras_ordenes_g1 = new HashSet<C_compras_ordenes_g>();
            this.C_almacen_solicitudes_mercancia_d_logs = new HashSet<C_almacen_solicitudes_mercancia_d_logs>();
            this.C_envios_leche_programacion_semanal_cliente_d_dias_horas = new HashSet<C_envios_leche_programacion_semanal_cliente_d_dias_horas>();
            this.C_evaluaciones_d_calificaciones = new HashSet<C_evaluaciones_d_calificaciones>();
            this.C_nomina_checador_prenomina = new HashSet<C_nomina_checador_prenomina>();
            this.C_nomina_checador_hrs_extras_estimulos = new HashSet<C_nomina_checador_hrs_extras_estimulos>();
            this.C_dashboard_usuarios = new HashSet<C_dashboard_usuarios>();
            this.C_alimentacion_tracker_articulos_ingredientes = new HashSet<C_alimentacion_tracker_articulos_ingredientes>();
            this.C_alimentacion_dietas_g = new HashSet<C_alimentacion_dietas_g>();
            this.C_alimentacion_dietas_g1 = new HashSet<C_alimentacion_dietas_g>();
            this.C_alimentacion_dietas_g2 = new HashSet<C_alimentacion_dietas_g>();
            this.C_alimentacion_dietas_g3 = new HashSet<C_alimentacion_dietas_g>();
            this.C_compras_cotizaciones_articulos = new HashSet<C_compras_cotizaciones_articulos>();
            this.C_compras_cotizaciones_confirmadas_g = new HashSet<C_compras_cotizaciones_confirmadas_g>();
            this.C_compras_cotizaciones_requisiciones = new HashSet<C_compras_cotizaciones_requisiciones>();
            this.C_compras_cotizaciones_requisiciones1 = new HashSet<C_compras_cotizaciones_requisiciones>();
            this.C_inventario_almacen_devoluciones_g = new HashSet<C_inventario_almacen_devoluciones_g>();
            this.C_sistemas_equipos_g = new HashSet<C_sistemas_equipos_g>();
            this.C_sistemas_equipos_g1 = new HashSet<C_sistemas_equipos_g>();
            this.C_salida_ganado_g = new HashSet<C_salida_ganado_g>();
            this.C_salida_ganado_logs_g = new HashSet<C_salida_ganado_logs_g>();
            this.C_salida_ganado_logs_g1 = new HashSet<C_salida_ganado_logs_g>();
            this.C_inventario_almacen_mov_d_recepciones_logs = new HashSet<C_inventario_almacen_mov_d_recepciones_logs>();
            this.C_soporte_tickets_d = new HashSet<C_soporte_tickets_d>();
            this.C_soporte_tickets_g = new HashSet<C_soporte_tickets_g>();
            this.C_soporte_logs = new HashSet<C_soporte_logs>();
            this.C_usuarios_cuentas_contables = new HashSet<C_usuarios_cuentas_contables>();
            this.C_compras_ordenes_precarga_g = new HashSet<C_compras_ordenes_precarga_g>();
            this.C_compras_ordenes_precarga_g1 = new HashSet<C_compras_ordenes_precarga_g>();
            this.C_compras_ordenes_recepciones_g = new HashSet<C_compras_ordenes_recepciones_g>();
            this.C_envios_leche_calidad = new HashSet<C_envios_leche_calidad>();
        }
    
        public int id_usuario_corporativo { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual C_usuarios_roles C_usuarios_roles { get; set; }
        public virtual C_empleados C_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_establos> C_usuarios_establos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_modulos_sub_permisos_usuarios_asignados> C_modulos_sub_permisos_usuarios_asignados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_g> C_almacen_solicitudes_mercancia_g2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_almacenes_usuarios> C_almacen_almacenes_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_captura_g> C_inventario_almacen_captura_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_centros> C_usuarios_centros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores_bloqueos> C_compras_proveedores_bloqueos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_firmas_usuarios> C_firmas_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_firmas_usuarios_montos> C_firmas_usuarios_montos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_cambios_articulos> C_almacen_solicitudes_cambios_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requisiciones_links_autorizacion> C_compras_requisiciones_links_autorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_masters> C_usuarios_masters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g> C_compras_requi_g5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_g> C_inventario_almacen_mov_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_importacion_facturas_g> C_contabilidad_importacion_facturas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_cargos_contables> C_usuarios_cargos_contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_solicitudes_pago_g> C_contabilidad_solicitudes_pago_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_solicitudes_pago_g> C_contabilidad_solicitudes_pago_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_solicitudes_pago_g> C_contabilidad_solicitudes_pago_g2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_g> C_establos_caseta_logs_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_g> C_establos_caseta_logs_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_proveedores_portal_tokens> C_compras_proveedores_portal_tokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_logs_d_visita_taller> C_establos_caseta_logs_d_visita_taller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_checador> C_nomina_empleados_checador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_areas_nomina> C_usuarios_areas_nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_inasistencias> C_nomina_inasistencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_establos_caseta_vales_salida> C_establos_caseta_vales_salida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_almacenes_ubicaciones_entrega> C_almacen_almacenes_ubicaciones_entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_g> C_nomina_beta_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_beta_g> C_nomina_beta_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requi_g_solicita_autorizacion> C_compras_requi_g_solicita_autorizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_productores> C_alimentacion_productores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_empleados_solicitudes> C_nomina_empleados_solicitudes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_incidencias> C_nomina_incidencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_inversiones_programadas> C_compras_inversiones_programadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_inversiones_programadas> C_compras_inversiones_programadas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_lote_logs> C_envios_leche_lote_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_articulos_catalogo_bascula> C_articulos_catalogo_bascula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cliente_destinos> C_envios_leche_cliente_destinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_forrajes_facturas_g> C_alimentacion_forrajes_facturas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_lote_g> C_envios_leche_lote_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_articulos_precios> C_alimentacion_articulos_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_articulos_precios> C_alimentacion_articulos_precios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_precios> C_envios_leche_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_precios> C_envios_leche_precios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_diaria_g> C_envios_leche_programacion_diaria_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_g> C_envios_leche_programacion_semanal_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_programa_g> C_alimentacion_programa_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_confirmacion> C_envios_leche_confirmacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_g> C_envios_leche_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_bascula_fichas> C_bascula_fichas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g_comentarios> C_alimentacion_dietas_g_comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_departamentos_usuarios> C_evaluaciones_departamentos_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_empleados_bonos> C_evaluaciones_empleados_bonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_empleados_bonos> C_evaluaciones_empleados_bonos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_g> C_evaluaciones_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_contabilidad_ordenes_pago_g> C_contabilidad_ordenes_pago_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_empleados> C_evaluaciones_d_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_conceptos> C_evaluaciones_d_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_ajustes_g> C_inventario_almacen_ajustes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_cumplimiento_semanal_comentario> C_envios_leche_cumplimiento_semanal_comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_requisiciones_logs> C_compras_requisiciones_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_g> C_compras_ordenes_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_g> C_compras_ordenes_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_almacen_solicitudes_mercancia_d_logs> C_almacen_solicitudes_mercancia_d_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_programacion_semanal_cliente_d_dias_horas> C_envios_leche_programacion_semanal_cliente_d_dias_horas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_evaluaciones_d_calificaciones> C_evaluaciones_d_calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_prenomina> C_nomina_checador_prenomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_nomina_checador_hrs_extras_estimulos> C_nomina_checador_hrs_extras_estimulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_dashboard_usuarios> C_dashboard_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_tracker_articulos_ingredientes> C_alimentacion_tracker_articulos_ingredientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_alimentacion_dietas_g> C_alimentacion_dietas_g3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_articulos> C_compras_cotizaciones_articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_confirmadas_g> C_compras_cotizaciones_confirmadas_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_requisiciones> C_compras_cotizaciones_requisiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_cotizaciones_requisiciones> C_compras_cotizaciones_requisiciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_devoluciones_g> C_inventario_almacen_devoluciones_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sistemas_equipos_g> C_sistemas_equipos_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_sistemas_equipos_g> C_sistemas_equipos_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_g> C_salida_ganado_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_g> C_salida_ganado_logs_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_salida_ganado_logs_g> C_salida_ganado_logs_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_inventario_almacen_mov_d_recepciones_logs> C_inventario_almacen_mov_d_recepciones_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_soporte_tickets_d> C_soporte_tickets_d { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_soporte_tickets_g> C_soporte_tickets_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_soporte_logs> C_soporte_logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_usuarios_cuentas_contables> C_usuarios_cuentas_contables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_g> C_compras_ordenes_precarga_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_precarga_g> C_compras_ordenes_precarga_g1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_compras_ordenes_recepciones_g> C_compras_ordenes_recepciones_g { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_envios_leche_calidad> C_envios_leche_calidad { get; set; }
    }
}
