//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_masters
    {
        public int id_usuario_master { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public string correo { get; set; }
        public Nullable<int> id_usuario_master_accion { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
        public virtual C_usuarios_masters_acciones C_usuarios_masters_acciones { get; set; }
    }
}
