//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_usuarios_areas_nomina
    {
        public int id_usuario_area { get; set; }
        public Nullable<int> id_departamento_empleado { get; set; }
        public Nullable<int> id_usuario_corporativo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual C_nomina_departamentos C_nomina_departamentos { get; set; }
        public virtual C_usuarios_corporativo C_usuarios_corporativo { get; set; }
    }
}
