//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camiones
    {
        public string placas { get; set; }
        public string chofer { get; set; }
        public string des_cam { get; set; }
        public string obs_cam { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public Nullable<int> id_consecutivo { get; set; }
    }
}
