//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichas_sg
    {
        public string ficha { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string placas { get; set; }
        public string user_id { get; set; }
        public string prov_cli { get; set; }
        public string producto { get; set; }
        public string chofer { get; set; }
        public Nullable<decimal> peso1 { get; set; }
        public Nullable<decimal> peso2 { get; set; }
        public Nullable<decimal> peso_t { get; set; }
        public string obs_p1 { get; set; }
        public string obs_p2 { get; set; }
        public string tmov { get; set; }
        public Nullable<bool> termina { get; set; }
        public string folio { get; set; }
        public string remision { get; set; }
        public string cvemov { get; set; }
        public Nullable<bool> aplica { get; set; }
        public Nullable<bool> agrupada { get; set; }
        public string observacio { get; set; }
        public string cesp { get; set; }
        public string folio_inv { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public Nullable<System.DateTime> rtime_p1 { get; set; }
        public Nullable<System.DateTime> rtime_p2 { get; set; }
        public string noreg { get; set; }
        public Nullable<bool> olor { get; set; }
        public Nullable<bool> matext_lib { get; set; }
        public string particula { get; set; }
        public string empaque { get; set; }
        public string color { get; set; }
        public string humedad { get; set; }
        public string caducidad { get; set; }
        public Nullable<decimal> pacas { get; set; }
        public Nullable<decimal> corte { get; set; }
        public Nullable<bool> repase { get; set; }
        public Nullable<bool> floracion5 { get; set; }
        public Nullable<bool> descolorida { get; set; }
        public Nullable<bool> humedad18 { get; set; }
        public Nullable<bool> humedad12 { get; set; }
        public Nullable<bool> maleza { get; set; }
        public Nullable<bool> prhoja { get; set; }
        public string d1tab { get; set; }
        public string d2tab { get; set; }
        public string d3tab { get; set; }
        public string d4tab { get; set; }
        public string d5tab { get; set; }
        public Nullable<decimal> d1pac { get; set; }
        public Nullable<decimal> d2pac { get; set; }
        public Nullable<decimal> d3pac { get; set; }
        public Nullable<decimal> d4pac { get; set; }
        public Nullable<decimal> d5pac { get; set; }
        public Nullable<decimal> peso_ori { get; set; }
        public string pozo { get; set; }
        public Nullable<decimal> p_matsec { get; set; }
        public string fic_prov { get; set; }
        public Nullable<bool> Recibida { get; set; }
        public Nullable<decimal> imp_p1 { get; set; }
        public Nullable<decimal> imp_p2 { get; set; }
        public Nullable<decimal> reimpresion { get; set; }
        public Nullable<System.DateTime> rtime_ip1 { get; set; }
        public Nullable<System.DateTime> rtime_ip2 { get; set; }
        public Nullable<System.DateTime> rtime_rim { get; set; }
        public string terraplen { get; set; }
        public string arcina { get; set; }
        public string bunker { get; set; }
        public Nullable<bool> consumo { get; set; }
        public string maquilador { get; set; }
        public string sucursal { get; set; }
        public string propietario_camion { get; set; }
        public string predio_cliente { get; set; }
        public string destino { get; set; }
        public string tabla { get; set; }
        public string variedad { get; set; }
        public string ensilador { get; set; }
    }
}
