//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hr_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hr_employee()
        {
            this.att_punches = new HashSet<att_punches>();
        }
    
        public int id { get; set; }
        public int emp_pin { get; set; }
        public string emp_code { get; set; }
        public string emp_ssn { get; set; }
        public string emp_role { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string emp_username { get; set; }
        public string emp_pwd { get; set; }
        public string emp_timezone { get; set; }
        public string emp_phone { get; set; }
        public string emp_payroll_id { get; set; }
        public string emp_payroll_type { get; set; }
        public string emp_pin2 { get; set; }
        public byte[] emp_photo { get; set; }
        public string emp_privilege { get; set; }
        public string emp_group { get; set; }
        public Nullable<System.DateTime> emp_hiredate { get; set; }
        public string emp_address { get; set; }
        public string emp_address2 { get; set; }
        public int emp_active { get; set; }
        public Nullable<System.DateTime> emp_firedate { get; set; }
        public string emp_firereason { get; set; }
        public string emp_emergencyphone1 { get; set; }
        public string emp_emergencyphone2 { get; set; }
        public string emp_emergencyname { get; set; }
        public string emp_emergencyaddress { get; set; }
        public string emp_cardNumber { get; set; }
        public string emp_country { get; set; }
        public string emp_city { get; set; }
        public string emp_state { get; set; }
        public string emp_postal { get; set; }
        public string emp_fax { get; set; }
        public string emp_email { get; set; }
        public string emp_title { get; set; }
        public Nullable<decimal> emp_hourlyrate1 { get; set; }
        public Nullable<decimal> emp_hourlyrate2 { get; set; }
        public Nullable<decimal> emp_hourlyrate3 { get; set; }
        public Nullable<decimal> emp_hourlyrate4 { get; set; }
        public Nullable<decimal> emp_hourlyrate5 { get; set; }
        public Nullable<int> emp_gender { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public Nullable<int> emp_operationmode { get; set; }
        public Nullable<int> IsSelect { get; set; }
        public Nullable<int> iuser1 { get; set; }
        public Nullable<int> iuser2 { get; set; }
        public Nullable<int> iuser3 { get; set; }
        public string cuser1 { get; set; }
        public string cuser2 { get; set; }
        public string cuser3 { get; set; }
        public string remark { get; set; }
        public Nullable<int> emp_dept { get; set; }
        public Nullable<int> payclass_id { get; set; }
        public Nullable<int> schedule_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_punches> att_punches { get; set; }
    }
}
