//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRACKER_LOGEntities : DbContext
    {
        public TRACKER_LOGEntities()
            : base("name=TRACKER_LOGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_tracker_establos> C_tracker_establos { get; set; }
        public virtual DbSet<C_tracker_ingredientes_establos> C_tracker_ingredientes_establos { get; set; }
        public virtual DbSet<C_tracker_movimientos_tipos> C_tracker_movimientos_tipos { get; set; }
        public virtual DbSet<C_tracker_parametros> C_tracker_parametros { get; set; }
        public virtual DbSet<C_tracker_parametros_tipos> C_tracker_parametros_tipos { get; set; }
        public virtual DbSet<C_tracker_movimientos> C_tracker_movimientos { get; set; }
    }
}
