//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Master_SIIBEntities : DbContext
    {
        public Master_SIIBEntities()
            : base("name=Master_SIIBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SolPago> SolPago { get; set; }
        public virtual DbSet<SolPagoDetalle> SolPagoDetalle { get; set; }
        public virtual DbSet<RecFactura> RecFactura { get; set; }
    }
}
