//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base_forrajesEntities : DbContext
    {
        public base_forrajesEntities()
            : base("name=base_forrajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proveedo_B> Proveedo_B { get; set; }
        public virtual DbSet<fichas_si> fichas_si { get; set; }
        public virtual DbSet<fichas_sm> fichas_sm { get; set; }
        public virtual DbSet<fichas_sg> fichas_sg { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<camiones> camiones { get; set; }
        public virtual DbSet<no_pozos> no_pozos { get; set; }
        public virtual DbSet<Producto_B> Producto_B { get; set; }
        public virtual DbSet<proveedo> proveedo { get; set; }
    }
}
