//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class no_pozos
    {
        public int id_no_pozo { get; set; }
        public string no_pozo { get; set; }
        public string rstatus { get; set; }
        public Nullable<int> id_establo { get; set; }
    }
}
