//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_de
    {
        public string orden { get; set; }
        public string art { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string t_mon { get; set; }
        public Nullable<decimal> cantidad_s { get; set; }
        public string observa { get; set; }
        public string area { get; set; }
        public string cuenta { get; set; }
        public string des1_art { get; set; }
        public string des2_art { get; set; }
        public string uni_art { get; set; }
        public string marca { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public Nullable<System.DateTime> FechaEnt { get; set; }
        public Nullable<decimal> CantEnt { get; set; }
        public Nullable<System.DateTime> FechaSal { get; set; }
        public Nullable<decimal> CantSal { get; set; }
    }
}
