//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_ge
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string centro { get; set; }
        public string beta { get; set; }
        public string orden { get; set; }
        public string requi { get; set; }
        public string id_centro { get; set; }
        public string cargo { get; set; }
        public string prov { get; set; }
        public string no_autor { get; set; }
        public Nullable<bool> impresa { get; set; }
        public Nullable<System.DateTime> fecha_imp { get; set; }
        public string hora_imp { get; set; }
        public Nullable<int> cta_imp { get; set; }
        public Nullable<decimal> servicio { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public string user_reg { get; set; }
        public Nullable<bool> Recibido { get; set; }
        public Nullable<bool> Surtido { get; set; }
        public Nullable<decimal> UbicaEntrega { get; set; }
    }
}
