//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class precios
    {
        public string prov { get; set; }
        public string art { get; set; }
        public string parte_prov { get; set; }
        public Nullable<decimal> p_lista { get; set; }
        public Nullable<decimal> p_1 { get; set; }
        public Nullable<decimal> p_2 { get; set; }
        public Nullable<decimal> p_3 { get; set; }
        public string t_mon { get; set; }
        public Nullable<decimal> desc1 { get; set; }
        public Nullable<decimal> desc2 { get; set; }
        public Nullable<decimal> desc3 { get; set; }
        public Nullable<decimal> c_pago1 { get; set; }
        public Nullable<decimal> c_pago2 { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
    }
}
