//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_B
    {
        public string cveart { get; set; }
        public string desart { get; set; }
        public string unimed { get; set; }
        public string obsart { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
        public Nullable<int> id_reg { get; set; }
        public string cvecla { get; set; }
        public string codigo { get; set; }
    }
}
