//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedo
    {
        public string cvepro { get; set; }
        public string despro { get; set; }
        public string obspro { get; set; }
        public string contpro { get; set; }
        public string tel1pro { get; set; }
        public string tel2pro { get; set; }
        public string dompro { get; set; }
        public string cvecla { get; set; }
        public Nullable<bool> prov { get; set; }
        public Nullable<bool> cli { get; set; }
        public string rstatus { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
    }
}
