//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecFactura
    {
        public decimal RecFacturaID { get; set; }
        public string RecFacturaFactura { get; set; }
        public System.DateTime RecFacturaFecha { get; set; }
        public decimal RecFacturaSubtotal { get; set; }
        public decimal RecFacturaIVA { get; set; }
        public decimal RecFacturaIVA_Retenido { get; set; }
        public decimal RecFacturaIVA_RetPorc { get; set; }
        public decimal RecFacturaIVA_RetBase { get; set; }
        public decimal RecFacturaISR_Retenido { get; set; }
        public decimal RecFacturaISR_RetPorc { get; set; }
        public decimal RecFacturaISR_RetBase { get; set; }
        public decimal RecFacturaImporte { get; set; }
        public string RecFacturaMoneda { get; set; }
        public bool RecFacturaAplica { get; set; }
        public System.DateTime RecFacturaTregistro { get; set; }
        public string RecFacturaRstatus { get; set; }
        public System.DateTime RecFacturaRtime { get; set; }
        public string RecFacturaProv { get; set; }
        public string RecFacturaOrden { get; set; }
    }
}
