//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolPago()
        {
            this.SolPagoDetalle = new HashSet<SolPagoDetalle>();
        }
    
        public decimal SolPagoId { get; set; }
        public System.DateTime SolPagoFecha { get; set; }
        public decimal SolPagoImporte { get; set; }
        public string SolPagoNum_Cuenta { get; set; }
        public string SolPagoMoneda { get; set; }
        public string SolPagoReferencia { get; set; }
        public string SolPagoEstatus { get; set; }
        public string SolPagoRstatus { get; set; }
        public System.DateTime SolPagoRtime { get; set; }
        public string SolPagoRUser { get; set; }
        public short SolPagoCtaTxT { get; set; }
        public short SolPagoEstatusAuto1 { get; set; }
        public short SolPagoEstatusAuto2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolPagoDetalle> SolPagoDetalle { get; set; }
    }
}
