//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolPagoDetalle
    {
        public decimal SolPagoDetalleId { get; set; }
        public decimal SolPagoId { get; set; }
        public decimal SolPagoDetalleDocto_Ba_Id { get; set; }
        public decimal SolPagoDetalleDocto_CP_Id { get; set; }
        public decimal SolPagoDetalleConcepto_Ba_Id { get; set; }
        public string SolPagoDetalleNombre_Co { get; set; }
        public System.DateTime SolPagoDetalleFecha { get; set; }
        public string SolPagoDetalleRefer { get; set; }
        public decimal SolPagoDetalleImporte { get; set; }
        public decimal SolPagoDetalleMoneda_Id { get; set; }
        public string SolPagoDetalleNombre_Mo { get; set; }
        public string SolPagoDetalleClave_Fiscal { get; set; }
        public string SolPagoDetalleDescripcion { get; set; }
        public decimal SolPagoDetalleBeneficiario_Id { get; set; }
        public string SolPagoDetalleNombre_Be { get; set; }
        public string SolPagoDetalleCta_Banco { get; set; }
        public short SolPagoDetalleAuto1 { get; set; }
        public System.DateTime SolPagoDetalleAuto1_Fecha { get; set; }
        public string SolPagoDetalleAuto1_User { get; set; }
        public short SolPagoDetalleAuto2 { get; set; }
        public System.DateTime SolPagoDetalleAuto2_Fecha { get; set; }
        public string SolPagoDetalleAuto2_User { get; set; }
        public string SolPagoDetalleRstatus { get; set; }
        public System.DateTime SolPagoDetalleRtime { get; set; }
        public string SolPagoDetalleRuser { get; set; }
        public string SolPagoDetalleNombre_PF { get; set; }
        public string SolPagoDetalleTipoPersona { get; set; }
    
        public virtual SolPago SolPago { get; set; }
    }
}
